deis/controller

- rootfs/bin/boot
- rootfs/deis/settings.py
- rootfs/templates/confd_settings.py
> ref(controller): use kubernetes service discovery, remove publish loop

- .travis.yml
See https://github.com/Masterminds/glide/releases/tag/0.7.2
> chore(.travis.yml): update glide to 0.7.2

- .travis.yml
- Makefile
- _scripts/ci/deploy.sh
- manifests/deis-workflow-rc.yml
This is the minimal amount of automation necessary to get a Deis v2 component up for testing.
> feat(deploy.sh): push deisci/workflow:v2-alpha images from master

- rootfs/deis/settings.py
- rootfs/requirements.txt
- rootfs/scheduler/k8s.py
- rootfs/templates/confd_settings.py
Many changes are necessary to work with k8s 1.1.1 (k8s.py was written for 1.0.2). This still needs a lot of testing and fixing up, but I wanted to push it out in-progress so others could help test and tell me what I'm doing wrong. :-)
TODO:
> fix k8s.py scheduler

- rootfs/requirements.txt
See https://github.com/docker/docker-py/blob/master/docs/change_log.md#160
See also deis/deis#4774.
> chore(controller): update docker-py to 1.6.0

- rootfs/scheduler/k8s.py
reflects conventions used in our helm charts
> ref(k8s): rename name label to app, introduce heritage label

- rootfs/api/models.py
These functions are not used anywhere
* https://github.com/deis/workflow/search?utf8=%E2%9C%93&q=validate_comma_separated
* https://github.com/deis/workflow/search?utf8=%E2%9C%93&q=validate_domain&type=Code
> ref(models): remove unused functions

- rootfs/bin/boot
> fix(migrations): remove etcd migration code from boot

- docs/src/using-deis/deploying-an-application.md
> docs(using-deis): add admonition to install deis cli

- docs/src/installing-deis/installing-the-deis-platform.md
> docs(installing-deis): add helm target usage

- README.md
addresses @carmstrong's comment in #71
> docs(readme): update client installation docs

- docs/src/installing-deis/system-requirements.md
> docs(system-requirements): k8s only requires 10.0.0.0 address space

- .gitignore
- Makefile
- _tests/Makefile
- _tests/apps_test.go
- _tests/auth_test.go
- _tests/builds_test.go
- _tests/config_test.go
- _tests/domains_test.go
- _tests/healthcheck_test.go
- _tests/help_test.go
- _tests/keys_test.go
- _tests/limits_test.go
- _tests/package.go
- _tests/perms_test.go
- _tests/ps_test.go
- _tests/releases_test.go
- _tests/tags_test.go
- _tests/tests_suite_test.go
- _tests/users_test.go
- _tests/version_test.go
Porting the deis/deis [integration tests](https://github.com/deis/deis/tree/master/tests) to Deis v2 and [ginkgo](http://onsi.github.io/ginkgo/). 
I'm putting this out here early for feedback. My goal is to add the app tests, then get this merged so others can help flesh out the remaining tests.
Closes #77.
> Integration tests

- docs/src/installing-deis/installing-the-deis-platform.md
- docs/src/managing-deis/configuring-dns.md
> docs(installing-deis): add domain configuration

- .gitignore
- _tests/Makefile
- _tests/tests_suite_test.go
- conditionally set required environment variables in the Makefile
- check for the deis client binary
cc/ @mboersma
> fix(_tests): help setup testing environment

- rootfs/scheduler/k8s.py
Instead of assuming the container is running on the same host as the controller is running on, we pull the image down and inspect its ports. Surpisingly the API endpoints are the exact same from image and container config, so it wasn't that hard to fix.
closes #107
> fix(k8s): pull image from private registry and inspect image

- README.md
Remove outdated material about having to log into the cluster to test.
> chore(README): add pointer to docs

- .travis.yml
- _scripts/ci/bintray-template.json
> feat(ci): compile and upload darwin release

- docs/src/installing-deis/quickstart.md
also added Google Container Engine.
> docs(quickstart): remove untested providers

- README.md
- docs/src/using-deis/installing-the-client.md
> docs(README): update client dev build instructions

- docs/src/installing-deis/configuring-object-storage.md
- docs/src/installing-deis/quickstart.md
Fixes #63 
Fixes #3
(note that in #3, this closes the second and final bullet point)
> doc(quickstart.md,configuring-object-storage.md): start documenting object storage configs

- rootfs/scheduler/k8s.py
Fixes #157 and partially reverts #95 as well. Seems the Exception handling may have never worked due to _scale_app never returning an object
Sprinkled in debug information as well
> fix(scheduler): terminate all pods from previous release on deploy

- docs/src/roadmap/roadmap.md
> doc(*): strike references to rigger

- CONTRIBUTING.md
- docs/src/contributing/development-environment.md
- docs/src/contributing/testing.md
- docs/src/index.md
- docs/src/installing-deis/system-requirements.md
- docs/src/roadmap/release-checklist.md
- docs/src/roadmap/roadmap.md
- docs/src/roadmap/test-plan.md
- docs/src/understanding-deis/components.md
- docs/src/understanding-deis/concepts.md
- docs/src/using-deis/managing-an-application.md
> doc(*): strike references to CoreOS

- docs/src/contributing/triaging-issues.md
- docs/src/roadmap/release-checklist.md
- docs/src/understanding-deis/architecture.md
- docs/src/understanding-deis/components.md
Another PR that partially addresses #161
> doc(*): strike references to publisher

- docs/src/contributing/overview.md
More updates re: expansion of Deis across multiple repositories.
> doc(overview): update contributing overview

- docs/src/contributing/design-documents.md
These are minor edits-- once again to be more inclusive of multiple Deis projects.
> doc(design-doc): update design doc docs

- .gitignore
- _tests/auth_test.go
- _tests/keys_test.go
- _tests/tests_suite_test.go
This is a fork of #158, with the changes proposed at https://github.com/deis/workflow/pull/158/files#r48192595 made.
Closes https://github.com/deis/workflow/pull/158
> Test Improvements II

- docs/src/contributing/development-environment.md
> doc(dev-environment): remove reference to deis/deis

- docs/src/roadmap/planning-process.md
Partially addresses #185 
Requires #201 to be merged first.
> doc(planning-proces): update planning process docs

- _tests/builds_test.go
> feat(test): add deis build integration test that supports v2-alpha

- docs/src/installing-deis/quickstart.md
> docs(quickstart): document how to configure deis client

- _tests/apps_test.go
cc/ @michelleN - this helps with error reporting in the apps tests
> ref(apps_test.go): use gexec based command execution

- _tests/releases_test.go
- _tests/tests_suite_test.go
> fix(releases_test.go): uncomment integration tests for releases

- docs/src/using-deis/using-docker-images.md
- docs/src/using-deis/using-dockerfiles.md
- docs/themes/deis/base.html
this changes all references except those in the roadmap, which @slack is handling.
refs #185
> ref(docs): scrub references to deis/deis

- docs/src/roadmap/planning-process.md
- docs/src/roadmap/roadmap.md
Refs deis/workflow#223 for the alpha release. Will flesh this out with the
complete roadmap as we approach 2.0 release.
> Update roadmap docs for alpha release.

- rootfs/api/models.py
- rootfs/api/south_migrations/0026_auto__chg_field_config_tags__chg_field_config_values__chg_field_config.py
- rootfs/deis/settings.py
- rootfs/requirements.txt
Does not change any functionality and helps with other PRs
> chore(models): move from django-json-field to jsonfield for Django 1.9 compatibility

- _tests/apps_test.go
- _tests/auth_test.go
- _tests/builds_test.go
- _tests/config_test.go
- _tests/keys_test.go
- _tests/perms_test.go
- _tests/releases_test.go
- _tests/tests_suite_test.go
* better errors messages
* work out of temp directory
* debug mode
* etc.
> test(*): upgrade test support

- rootfs/api/models.py
- rootfs/api/utils.py
- rootfs/requirements.txt
- rootfs/scheduler/utils.py
Fixes #196
Router needs to have a PR that understands this format
> feat(k8s): use dotted format instead of JSON for router domain configuration

- rootfs/Dockerfile
http://alpinelinux.org/posts/Alpine-3.3.0-released.html
Ran a handful of commands on the new image, things appear to function properly
> chore(image): bump alpine to 3.3

- rootfs/scheduler/__init__.py
fixes https://github.com/deis/workflow/issues/154
> feat(workflow): add support to set memory and cpu configs

- client/cmd/limits.go
- rootfs/api/serializers.py
- rootfs/api/tests/test_config.py
- rootfs/scheduler/__init__.py
fixes https://github.com/deis/workflow/issues/244
> feat(workflow): add support for floating point cpus and milli cpu units

- rootfs/scheduler/__init__.py
base64encode returns a bytes object which is doesn't do so well with json serialization so I decode() it to string first
Causes a failure in all new apps
> fix(scheduler): python 3 b64 needs bytes but k8s api needs string passed

- rootfs/scheduler/__init__.py
> fix(scheduler): slug url was replacing : with -, which is not accurate

- client/pkg/git/git.go
- client/pkg/git/git_test.go
> fix(client): replace port in git remote creation

- rootfs/api/models/app.py
> chore(logs): Update logger endpoint URL

- README.md
Drop some bread crumbs for the friendly folks checking out Alpha.
> doc(README): document Kubernetes requirements

- rootfs/requirements.txt
See https://github.com/benoitc/gunicorn/compare/19.4.1...19.4.5
> chore(requirements.txt): update gunicorn to 19.4.5

- rootfs/scheduler/__init__.py
to create service we have to know port . 
This fixes logic for pulling deis pull app images and dockerfile type app images for inspecting Port
> fix(dockerpull): fix logic for image pull for dockerfile apps

- rootfs/requirements.txt
https://www.djangoproject.com/weblog/2016/feb/01/releases-192-and-189/
> chore(django): update Django to 1.9.2

- Makefile
- client/cmd/apps.go
- client/controller/models/apps/apps.go
- client/controller/models/apps/apps_test.go
- rootfs/deis/settings.py
This PR submits the necessary code changes to support the new v2 logger implementation.
> feat(logger): Support logger v2

- manifests/deis-workflow-service.yml
- rootfs/scheduler/__init__.py
> ref(workflow): Add namespace to routable label on app services

- client/Makefile
- client/glide.lock
- client/glide.yaml
Also, ignore appengine packages in the glide.yaml file
Fixes #339
cc/ @helgi
> fix(Makefile,glide.yaml,glide.lock): build client code inside a Docker container

- rootfs/api/tests/test_hooks.py
- rootfs/api/views.py
> feat(hooks): add fingerprint to key hooks API response

- rootfs/api/tests/test_hooks.py
- rootfs/api/urls.py
- rootfs/api/views.py
> feat(hooks): expose a ssh public key hook for builder to interact with

- client/controller/models/apps/apps.go
This fixes an incorrect URL in a help message.
> fix(client): Fix logger URL in logger help msg

- .travis.yml
- _scripts/ci/bintray-template.json
- client/Makefile
> fix(bintray): add unique version to bin name

- .travis.yml
- client/Makefile
> Revert "fix(make): get gox during bootstrap for use in build-all"

- .travis.yml
- client/Makefile
> Revert "Revert "fix(make): get gox during bootstrap for use in build-all""

- client/cmd/ps.go
- client/controller/api/ps.go
- client/controller/models/ps/ps.go
- client/controller/models/ps/ps_test.go
- client/parser/ps.go
- rootfs/api/models/app.py
- rootfs/api/serializers.py
- rootfs/api/urls.py
- rootfs/api/views.py
- rootfs/scheduler/__init__.py
- rootfs/scheduler/mock.py
Fetches all the information directly from k8s and uses the pod name in the output. Can no longer do a limit fetch as the k8s API does not support it
Fixes #160
> feat(ps): query k8s to get the ps:list information instead of db

- rootfs/requirements.txt
https://docs.djangoproject.com/en/1.9/topics/i18n/timezones/ recommended
> feat(tz): add pytz as a requirement to get better timezone data (Olsen DB)

- docs/requirements.txt
See http://www.mkdocs.org/about/release-notes/#version-0152-2016-02-08
> chore(docs/requirements): update MkDocs to 0.15.2

- rootfs/requirements.txt
See https://github.com/docker/docker-py/blob/master/docs/change_log.md#170
I've tested this locally with the e2e suite and didn't find any new problems.
> chore(requirements): update docker-py to 1.7.0

- rootfs/api/models/config.py
- rootfs/scheduler/__init__.py
timeouts and delays defaults to 50 seconds
> feat(healthcheck): remove default healthcheck for apps

- rootfs/templates/confd_settings.py
refs deis/postgres#36
refs deis/charts#98
> feat(settings): read database credentials from k8s secret

- .travis.yml
Needed to update path to bintray-ci.json after moving template into client
> fix(.travis.yml): update bintray-ci.json location

- client/cmd/auth.go
> fix(client): only delete local ~/.deis/client.json if cancelling logged in user

- docs/src/understanding-deis/components.md
> docs(understanding-deis): document database lifecycle

- rootfs/scheduler/__init__.py
- Identifies POD_Template.
- Timesout after 90 seconds , 30 seconds if POD state is not in running 
Tested with docker file and buildpack app
> feat(run): implement deis run

- client/cmd/apps.go
> fix(logs): Update the array index for determining the color category

- rootfs/scheduler/__init__.py
The idea here is to introduce far more comprehensive logging on scale operations to give both better insight into where scaling is slow and generally give an operator an idea of what step it is on.
I've tested a normal scale up and scale down + a deploy using `config:set` but only on docker images
> ref(scheduler): improve scale operation logging and performance

- client/cmd/config.go
- client/parser/config.go
> feat(config): add pipe suport to config:pull

- rootfs/api/models/app.py
> fix(scheduler): if a pod is in pending there is no start time, instead use now()

- rootfs/requirements.txt
See https://github.com/docker/docker-py/blob/master/docs/change_log.md#172
> chore(reqs): update docker-py to 1.7.2

- rootfs/api/models/app.py
- rootfs/scheduler/__init__.py
Also update `_get_job_id` to be more like the format we expect so transformations do not need to happen inside the scheduler
> ref(scheduler): use proper k8s naming (namespace vs app_name) and pass that in properly

- rootfs/requirements.txt
https://docs.djangoproject.com/en/1.9/releases/1.9.3/
> chore(django): bump to django 1.9.3

- rootfs/api/models/certificate.py
> fix(models): catch proper kube exceptions in certficates so secrets get created

- Makefile
run `make deploy` after a `git commit` to roll the image, apply it and scale to whatever replica count the component was set to.
Does not touch helm, only uses the already applied information from k8s
> feat(make): make deploy to apply the latest RC image for workflow

- client/controller/models/apps/apps.go
- rootfs/deis/settings.py
1. install deis-dev
1. install deis-logger
1. restart workflow
1. create app of your choice
1. trigger log creation
1. run `deis logs` on said app
1. make sure logs show up
> fix(logger): Update the port that workflow uses to find logger

- rootfs/scheduler/__init__.py
Application type information is acquired differently now
> chore(scheduler): remove dead code. loc is used in v1 to get mem/cpu etc

- rootfs/scheduler/__init__.py
Changed things around so that first we ensure there are enough pods running to service the desired state and then verify that all pods are terminated
The reason to move away from events is that the API server (k8s one) has a watch setup on etcd to see events fly by but also utilises a fairly constrained cache of the information to speed things up. On more active k8s servers the information can go stale within seconds or drops off the radar very quickly.
More info at https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/apiserver-watch.md#high-level-design
Fixes #484
> fix(scheduler): stop relying on namespace events in k8s for scale information

- rootfs/api/models/certificate.py
Before the code would delete the secret on every detach but now instead it checks if there are any domains associated still with the certificate before deleting.
It can do so before the association between domain and cert is nulled out a few lines up.
This wasn't caught since the exception rule is to log the error instead of blowing up. There are tests that expose this behaviour but only against a real k8s cluster
> fix(certificates): only delete k8s secrets for certs when last domain associated is detached

- Makefile
Images will now get pushed to deisci/controller
refs https://github.com/deis/deis/issues/4952
TODO:
> ref(Makefile): change component name to controller

- Makefile
fixes https://github.com/deis/workflow/pull/494#issuecomment-195502694
> ref(Makefile): stop hardcoding component name

- .travis.yml
- README.md
- rootfs/dev_requirements.txt
See https://codecov.io/github/deis/workflow
Closes #442 
Example of how PRs could start looking https://github.com/pyca/cryptography/pull/2805
> feat(tests): use codecov.io for visual code coverage reporting

- rootfs/scheduler/__init__.py
> fix(scheduler) scheduler stops a scale operation early if desired is the same as current number of pods

- README.md
cc/ @helgi @mboersma @slack 
Ref https://github.com/deis/deis/issues/4962
> doc(README.md): update README to reflect beta status

- README.md
> docs(README): fix up language about merging PRs

- rootfs/deis/settings.py
- rootfs/scheduler/__init__.py
https://github.com/deis/charts/pull/164
> feat(slugrunner): make slugrunner configurable via env variables

- rootfs/api/models/app.py
Rationale here is that the RC already has the desired information and we may be iterating over many RCs.
Not using the pod count is helpful in case other operations happen to have interfered with things.
Another option is to use the structure info from the App model but this solutions seems more solid
Also moved some filtering into a shared function
> ref(apps): iterate over RC for desired pod count when doing an app restart

- README.md
The component name has changed to deis/controller but the README
had not yet been updated.
closes #528
> docs(README): update component information

- README.md
see https://github.com/deis/controller/pull/530/files#r56587597
> fix(README): revert template changes

- rootfs/Dockerfile
- rootfs/conf.d/local_settings.toml
- rootfs/templates/local_settings.py
> fix(confd): Fix user registration disabling

- README.md
Updates controller documentation to reflect deis/charts#157
> fix(README): update charts to use workflow-dev instead of deis-dev

- rootfs/api/tests/test_config.py
Does not actually verify much on the backend yet, until the tests start reaching into k8s
> chore(tests): a simple k8s healthchecks test

- rootfs/scheduler/__init__.py
Right now there is an assumption that the first container in a Pod is the Deis application container. While not wrong it is better to find the right container and only apply to it
Fixes #518
> fix(scheduler): apply healthcheck to the right application container instead of assuming

- rootfs/api/models/config.py
- rootfs/api/tests/test_config.py
Improved the error message and call out the new tag(s) that are causing the problem
Fixes #486
> fix(tags): improve the error message when the combination of tags match no node labels

- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
- rootfs/api/views.py
- rootfs/scheduler/mock.py
> fix(app): check if app name already exists in kubernetes during app creation

- rootfs/requirements.txt
See http://www.django-rest-framework.org/topics/release-notes/#333
> chore(requirements): update DRF to 3.3.3

- rootfs/scheduler/__init__.py
- rootfs/scheduler/mock.py
pass storage parameters to slugrunner
Fixes #458
Fixes #521
> feat(slugrunner): pass storage parameters to slugrunner

- rootfs/scheduler/__init__.py
pass minio details to slugrunner during pod created during run command
> fix(slugrunner): pass minio details to slugrunner during run command

- rootfs/api/tests/test_app.py
- rootfs/api/tests/test_pods.py
- rootfs/scheduler/__init__.py
> fix(scheduler): deis run can fail under some conditions when DEBUG is set

- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
- rootfs/scheduler/__init__.py
> fix(scheduler): only update port on routable services

- rootfs/deis/settings.py
- rootfs/scheduler/__init__.py
> feat(scheduler): make the image fetching policy for slugs and docker images configurable via ENV vars

- rootfs/api/models/config.py
- rootfs/scheduler/__init__.py
This both helps the end user to see what the other healthcheck values are and saves the state to the DB, that way platform upgrades will not suddenly change defaults from undernearth users
```
controller  (health>) $ deis config:set HEALTHCHECK_URL=/health -a excess-ziggurat
Creating config... done
=== excess-ziggurat Config
HEALTHCHECK_INITIAL_DELAY      50
HEALTHCHECK_PORT               5000
HEALTHCHECK_TIMEOUT            50
HEALTHCHECK_URL                /health
Helgi                          Foo
Helgi_Hi                       Foo
controller  (health>) $ deis config:set HEALTHCHECK_PORT=5001 -a excess-ziggurat
Creating config... done
=== excess-ziggurat Config
HEALTHCHECK_INITIAL_DELAY      50
HEALTHCHECK_PORT               5001
HEALTHCHECK_TIMEOUT            50
HEALTHCHECK_URL …
```
> feat(config): setting one healthcheck value now results in all defaults for health to be saved

- rootfs/scheduler/__init__.py
> feat(k8s): base64 decode secrets on the fly and insert into response

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.9/releases/1.9.5/
> chore(requirements): update Django to 1.9.5

- rootfs/api/models/release.py
- rootfs/api/tests/test_build.py
- rootfs/api/tests/test_release.py
> feat(release): re-use image source if Build is called with an image that is already in the deis registry

- rootfs/requirements.txt
https://github.com/docker/docker-py/blob/master/docs/change_log.md#180
> chore(requirements): update docker-py to 1.8.0

- rootfs/api/models/app.py
- rootfs/api/views.py
- rootfs/scheduler/__init__.py
Same as the change around `deploy`
> fix(views): use Exception instead of RuntimeError in view around rollbacks

- .github/PULL_REQUEST_TEMPLATE
This pull request template describes the typical workflow each
pull request goes through. This just formalizes it so users and
core contributors have a checklist to go through when reviewing
pull requests.
> feat(github): add pull request template

- rootfs/api/models/release.py
This will reduce the occurance of stray RCs when the Release record is nuked, due to whatever problems may arise
I believe this will help with #319 and possibly others
Somewhat hard to test this one since it is not possible to trigger a Release model delete without causing havoc in other places, which we also try to prevent
> fix(release): attempt to delete stray RCs when Release DB model does a delete

- rootfs/api/models/release.py
> fix(release): versions are stored with v appended in the RC version

- rootfs/api/management/commands/load_db_state_to_k8s.py
- rootfs/api/models/certificate.py
http://kubernetes.io/docs/user-guide/ingress/#tls
Fixes #576 
/cc @aledbf @krancour 
Requires a router changes as per my description in #576
> feat(k8s): match cert data structure to the TLS one for Ingress

- CHANGELOG.md
This PR adds a changelog entry for the `v2.0.0-beta2` release
None
None
None
None
None - this is a documentation patch only.
> doc(CHANGELOG.md): add changelog entry for beta2

- rootfs/api/views.py
> ref(views): consolidate all views::create handling into one create function

- rootfs/scheduler/__init__.py
Add readiness probe which check whether the downloded slug has started running
2. deploy a build pack app and simultaneously do watch on kubectl get pods in another window
3. Once the app is deployed you should see a state where the pod is in running state but doesn't show it as ready.
> feat(slugrunner): add readiness check for the slugrunner pod

- rootfs/api/models/app.py
Deploy should be successful even when web doesn't exist as proc type in the procfile for a buildpack app.
2. deploy a buildpack app with proc type as test or anything other than web
3. app should get successfully deployed
> fix(deploy): should deploy successfullly without web type in the procfile

- rootfs/scheduler/__init__.py
Add readiness check for the docker app container
2. Register an docker file/deis pull app
3. It should work fine and you should see a readiness check when you describe the pod
> feat(dockerapp): add default readiness check for the docker file app

- rootfs/api/models/config.py
Moves tags validation out of `save` directly and uses a `set_*` convention used for `healthchecks` and `registry`
> ref(config): validate tags in the same way as healthchecks and registry

- rootfs/api/models/release.py
Simplifies the control flow in `publish`
> ref(release): return earlier if build pack or dockerfile app is being used

- rootfs/api/models/app.py
> fix(app): catch connection timeout exceptions during appliation health verification

- rootfs/scheduler/__init__.py
Removes a hardcoding of a wait in the scheduler, can make restarts faster
> ref(scheduler): use termination grace period for Pod delete

- rootfs/scheduler/__init__.py
The code was naively checking if any pods were in the current RC but did not check if they were actually ready. This poses a problem for deploys
> fix(scheduler): check if the pods are ready in scale up operations before comparing to desired state

- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
> fix(app): response object was not accessible if app verification threw request exception

- rootfs/requirements.txt
Updates the standard pytz time zone database to the current data set.
> chore(requirements): update pytz to 2016.4

- rootfs/dev_requirements.txt
Updates the codecov uploader library to the current release, 2.0.3
See https://github.com/codecov/codecov-python/compare/v1.6.3...v2.0.2
> chore(requirements): update codecov lib to 2.0.3

- rootfs/api/models/app.py
- rootfs/deis/settings.py
> ref(deploy): rename DEPLOY_BATCHES to DEIS_DEPLOY_BATCHES

- codecov.yml
> feat(coverage): use yaml file for codecov.io

- README.md
https://www.versioneye.com/user/projects/5728e1dba0ca350034be67be for info
> chore(versioneye): add version eye integration

- rootfs/requirements.txt
https://docs.djangoproject.com/en/1.9/releases/1.9.6/
> chore(requirements): Django 1.9.6

- rootfs/requirements.txt
https://github.com/docker/docker-py/blob/master/docs/change_log.md#181
> chore(requirements): update docker-py to 1.8.1

- rootfs/api/serializers.py
CI rarely (if ever) reached the float loop
> ref(validation): do float validation in the regex for CPU shares

- rootfs/scheduler/__init__.py
By default kubernetes will mark a readiness probe as Failure if initial delay is set on it, until the delay is over.
Many users will add initial delay so that their application can warm up caches, on pod
Part addresses #706
Best way to test this is to do `config:set HEALTHCHECK_URL=/ HEALTHCHECK_INITIAL_DELAY=120` on a deployed application, then go into the Controller logs and verify that the following messages show up:
* `adding {}s on to the original {}s timeout to account for the initial delay specified in the readiness probe for the RC`
* and the timeout message below it, it should say `timeout 240s` as the initial time we give it is 120 (120+120 = 240 :))
> fix(deploy): account for readiness initial delay when determining if a pod is ready

- rootfs/scheduler/__init__.py
Also return the response object from _create_rc for consistency with rest of the scheduler
> ref(scheduler): move "is RC ready" into a new function

- rootfs/requirements.txt
https://github.com/sigmavirus24/requests-toolbelt/blob/master/HISTORY.rst#061----2016-05-05
> chore(requirements): update requests-toolbelt to 0.6.1

- rootfs/api/models/release.py
- rootfs/scheduler/__init__.py
Scaling an RC to 0 and deleting it does not always clear up all the active pods. This can happen if there is an image pull problem
> feat(scheduler): clean up stray pods when a release is deleted

- rootfs/api/models/build.py
delete the build if an exception occurs while doing a new release for the build.
2. Deploy a docker app without exposing any port and proc file so that the controller will raise an exception and the build fails.
3. change the docker file to expose the port  and do the deploy again.The deploy should succeed this time with the code changes.
> fix(builds):User should be able to do a deploy an app after a failed attempt

- CONTRIBUTING.md
- README.md
change the reference of helm to helm classic
Please list the issue(s) that this PR closes, similar to the below:
Just the docs changes
> docs(helmc): update the docs to use helm classic instead of helm

- rootfs/requirements.txt
https://github.com/sigmavirus24/requests-toolbelt/blob/master/HISTORY.rst#062----2016-05-10
> chore(requirements) update requests-toolbelt to 0.6.2

- rootfs/api/tests/test_pods.py
- rootfs/bin/boot
- rootfs/scheduler/__init__.py
refs https://github.com/deis/workflow/issues/178
> ref(rootfs): rename DEBUG to DEIS_DEBUG

- rootfs/Dockerfile
- rootfs/scheduler/__init__.py
Updated `DEIS_RELEASE` to be `WORKFLOW_RELEASE` as done similarly elsewhere (see https://github.com/deis/workflow/pull/193)
TODO
> chore(Dockerfile,__init__.py): DEIS_RELEASE -> WORKFLOW_RELEASE

- rootfs/requirements.txt
http://docs.gunicorn.org/en/stable/news.html
> chore(requirements): Update Gunicorn to 19.5.0

- rootfs/api/models/app.py
- rootfs/api/models/release.py
- rootfs/api/tests/test_app.py
- rootfs/api/tests/test_build.py
- rootfs/api/tests/test_config.py
- rootfs/api/tests/test_hooks.py
- rootfs/api/tests/test_pods.py
- rootfs/api/tests/test_release.py
- rootfs/scheduler/__init__.py
> fix(scheduler): move _get_port to use docker functions to split image info

- rootfs/scheduler/__init__.py
> fix(scheduler): waiting state does not always have a message

- rootfs/dev_requirements.txt
https://bitbucket.org/ned/coveragepy/src/tip/CHANGES.rst?fileviewer=file-view-default
> chore(requirements): update coverage to 4.1

- CHANGELOG.md
> feat(changelog): update changelog to v2.0.0-rc1

- rootfs/Dockerfile
https://pip.pypa.io/en/stable/news/
> chore(Dockerfile): update pip to 8.1.2

- rootfs/Dockerfile
Also speed up apt-get update by disabling source repos
If https://github.com/deis/docker-base/pull/2 gets merged then the optimisation can be removed from this repo
> ref(image): handle Dockerfile build deps via variables

- rootfs/requirements.txt
https://docs.djangoproject.com/en/1.9/releases/1.9.7/
> chore(requirements): update to Django 1.9.7

- rootfs/api/serializers.py
- rootfs/api/tests/test_config.py
This validates that the `PORT` is an int and within the acceptable port range.
`HEALTHCHECK_URL` has a special validation due to Kubernetes constraints we found in #774 - Basically only supports `path`
Please list the issue(s) that this PR closes, similar to the below:
Fixes #774
Fixes #777
Fixes #781
https://github.com/deis/workflow/pull/286
The Controller tests take care of this
> feat(config): validate PORT and HEALTHCHECK_* values for config:set operations

- rootfs/registry/dockerclient.py
- rootfs/requirements.txt
Uses the jitter function for the wait time https://github.com/litl/backoff#jitter
Ref #708
> ref(docker): change retry library to backoff

- rootfs/api/models/config.py
This helps mitigate #798 for day to day use (quick fix) as the previous config is no longer pulled from the top of the application config stack and instead pulls the latest release config.
Doing that will prevent the logic from re-using a potentially broken Config object. When a Release object is deleted an Config object can be orphaned but still available.
refs #798 
Ideally this change should be tested as part of https://github.com/deis/controller/pull/792 as that PR has the failure condition required (and the commit from this PR) but I decided that it was better to get them merged individually.
> fix(config): when rolling a new config copy from the latest release instead of latest config for the app

- rootfs/api/settings/production.py
DEIS_DEBUG not being set or being an empty string = False, otherwise it is True
> feat(debug): DEIS_DEBUG now affects Django DEBUG as well

- rootfs/scheduler/__init__.py
https://github.com/kubernetes/kubernetes/blob/master/docs/devel/api-conventions.md#metadata explains the resourceVersion and generation pretty well
resourceVersion is the internal version representation where as generation deals with desired state
Some resources report the observedGeneration, which is the generation most recently observed by the component responsible for acting upon changes to the desired state of the resource. This can be used, for instance, to ensure that the reported status reflects the most recent desired status.
This is also how to determine if Deployments are ready so it's good to match it all up
> ref(scheduler): use observedGeneration instead of resourceVersion for RC readiness

- rootfs/api/models/__init__.py
- rootfs/api/models/app.py
- rootfs/api/models/certificate.py
- rootfs/api/models/config.py
- rootfs/api/models/release.py
- rootfs/api/tests/test_domain.py
- rootfs/api/tests/test_pods.py
- rootfs/scheduler/__init__.py
- rootfs/scheduler/mock.py
Many were already being used in the Models - Time to make it more official
> ref(scheduler): move a lot of scheduler functions from private to public

- rootfs/scheduler/__init__.py
ReplicationController can take a fully formed Pod Template (include Kind / apiVerison) within its spec/template section
This allows reuse of the Pod Template between deis run and RCs (and Deployments in the future).
The distinction between buildpack and "the rest" templates was eliminated by moving more of the env var and volume logic into the build pod template and set container functions.
This may not seem like a lot but it will help reduce code duplication (and template duplication) going forward, especially when I add Deployments
> ref(scheduler): introduce a build pod template function to reduce duplication in scheduling code

- rootfs/requirements.txt
Updates a dependency with a minor clerical patch release so the badge goes green again: [![Dependency Status](https://www.versioneye.com/user/projects/5728e1dba0ca350034be67be/badge.svg?style=flat)](https://www.versioneye.com/user/projects/5728e1dba0ca350034be67be)
See https://github.com/cedadev/ndg_httpsclient/#041 and https://github.com/cedadev/ndg_httpsclient/compare/v0.4.0...0.4.1
> chore(requirements): update ndg-httpsclient to 0.4.1

- rootfs/api/models/__init__.py
- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
Spelling fixes
n/a
Not opened yet (will update when I have a PR #)
n/a
n/a
n/a
> fix(models): hypens -> hyphens

- rootfs/api/__init__.py
Bumps the API version for the new release.  This also needs corresponding controller-sdk-go, CLI, and documentation PRs. 
n/a
n/a
Will be updated when it is opened.
DEIS_API_VERSION header should equal `2.1`
> chore(api): bump api version to v2.1.0

- rootfs/Dockerfile
This is no longer necessary.
refs deis/workflow#356
> ref(Dockerfile): remove WORKFLOW_RELEASE envvar

- rootfs/api/models/app.py
- rootfs/api/tests/test_pods.py
Handle the case of validation error instead of value error as it value error re-thrown as validation error in the validate function.
fixes #831
3. Try to call the scale endpoint as mentioned in the #831 and you should get a proper json error response.
> fix(scale): return error message in proper format

- rootfs/requirements.txt
http://initd.org/psycopg/articles/2016/07/07/psycopg-262-released/
> chore(requirements): update psycopg

- rootfs/requirements.txt
https://bitbucket.org/ruamel/yaml/src see changelog at the bottom
> chore(requirements): update ruamel.yaml to 0.11.14

- rootfs/api/models/app.py
- rootfs/scheduler/__init__.py
The scheduler's k8s API access and app.py's healthcheck calls would create a new [`requests.Session`](http://docs.python-requests.org/en/master/user/advanced/#session-objects) with each class used, resulting in many `urllib3` allocations as printed in the controller logs. Since `Session` persists parameters and cookies and uses connection pooling, creating and destroying it often isn't optimal usage.
This refactoring moves the two usages of `Session` into module-level objects with a `get`ter method--the cheap way of making an object a singleton in python.
After this change, I don't see large blocks of connection allocations in the controller logs any more, but I do see this sometimes, which means it's working:
```console
INFO:requests.packages.urllib3.connectionpool:Resetting dropped …
```
> ref(*): use requests.Session as a singleton

- rootfs/api/models/certificate.py
- rootfs/scheduler/__init__.py
Move to the same model as Pod building. Also moves update secret to generate a whole new object to overwrite the previous one instead of just updating the data element
Unifies the base64 encoding and how labels are applied
This may help fix #862
> ref(scheduler): generate secrets manifest for create and update secrets

- rootfs/scheduler/__init__.py
Mostly a clarification of a few function names and simplify a few wait functions
> ref(scheduler): simplify RC wait logic and container info around that

- rootfs/api/models/domain.py
- rootfs/api/models/key.py
Fixes #848
Fixes #849
I'm sure more can be done, mostly illustrating the fix
> fix(models): better error messages than the built in Django ones for a few of the fields

- rootfs/scheduler/__init__.py
Look at the e2e controller logs to see it in its glory or do any action locally that triggers a scheduler action, it should now be prepended with `[foobar] hello i am a message`
> feat(scheduler) prepend [namespace] to Scheduler log message for better traceability

- rootfs/api/tests/deployments/test_domain.py
- rootfs/api/tests/test_domain.py
> fix(tests): sort domains in tests to get past occasional ordering problems which cause test failures

- rootfs/deis/__init__.py
> feat(version): bump version to v2.2.0

- rootfs/requirements.txt
https://pypi.python.org/pypi/ndg-httpsclient
> chore(requirements): update ndg-httpsclient to 0.4.2

- rootfs/requirements.txt
https://github.com/sigmavirus24/requests-toolbelt/blob/master/HISTORY.rst
> chore(requirements): update requests-toolbelt to 0.7.0

- rootfs/api/tests/test_auth.py
- rootfs/api/urls.py
- rootfs/api/views.py
supercedes #543 
closes deis/deis#4792
TODO:
> feat(api): added auth/whoami endpoint

- rootfs/api/models/release.py
e2e test: https://github.com/deis/workflow-e2e/pull/273
> fix(release): old release shouldn't be deleted if new release fails

- rootfs/scheduler/__init__.py
This is a bit of a weird since it is not easy to trigger this bug. This is a best attempt at fixing without being able to trigger it.
Fixes #897
> fix(scheduler): only get logs for run pods when possible

- rootfs/api/tests/test_certificate.py
- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/3.4-announcement/
Not making use of any of the new functionalities in this change. Those can come later
Requires deis/workflow-e2e#272
> chore(requirements): update Django REST Framework to 3.4.0

- rootfs/api/models/build.py
e2e: https://github.com/deis/workflow-e2e/pull/273
> fix(pull): release and build should be deleted on failed deis pull

- .github/PULL_REQUEST_TEMPLATE
> docs(PR Template): switch from refs to requires as per new syntax

- rootfs/api/models/release.py
- rootfs/api/tests/deployments/test_build.py
- rootfs/api/tests/test_build.py
> fix(registry): User should be able to pull the image from internal registry

- Makefile
> ref(makefile): update make deploy to account for Controller using Deployment instead of RC

- README.md
Adds instructions on how to get started developing on Debian Jessie.
> doc(README): add debian installation instructions

- rootfs/api/management/commands/load_db_state_to_k8s.py
- rootfs/api/models/app.py
I did not manage to get my cluster into this state to properly test it. I may have too small of a cluster
The repro steps can be found at #903
Fixes #903
/cc @arschles
> fix(boot): show a warning instead of error if a Deployment is in progress when Deis Workflow is starting up

- rootfs/scheduler/__init__.py
> fix(scheduler): check if an event stream was returned before pop()ing it

- rootfs/registry/dockerclient.py
Based on data found in https://gist.github.com/slack/09d11a6986e4e9a8d939ad22204a1be3
> fix(registry): catch docker timeouts and show a nicer error

- rootfs/requirements.txt
https://github.com/docker/docker-py/blob/master/docs/change_log.md#190
> chore(requirements): update to docker-py 1.9.0

- rootfs/dev_requirements.txt
See https://coverage.readthedocs.io/en/coverage-4.2/changes.html#version-4-2-2016-07-26
> chore(dev_requirements): update coverage lib to 4.2.0

- rootfs/api/models/app.py
- rootfs/api/tests/deployments/test_app.py
- rootfs/api/tests/test_app.py
- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#341
Requires deis/workflow-e2e#279
> chore(requirements): Update to DRF 3.4.1

- rootfs/api/management/commands/load_db_state_to_k8s.py
Adapts deis/deis#5028 to Deis Workflow controller v2. All credit goes to @jgmize.
> fix(controller): only load latest config

- rootfs/api/models/app.py
- rootfs/api/utils.py
This also moves the restart function to use api.utils.async_run  - it is a slightly modified version of the original to be exception aware and not require an internal function
Eventually I may move us to use https://github.com/observerss/aioutils but right now that is not required
> feat(apps): scale / deploy run all process types in parallel instead of sequantially

- rootfs/api/__init__.py
The auth/whoami endpoint was added.
Replaces https://github.com/deis/controller/pull/929
Requires deis/workflow-cli#157
> chore(api): bump api version to v2.2.0

- rootfs/scheduler/__init__.py
this behavior is changed in k8s 1.3.4.
> fix(secret): handle the secret value if it is None

- rootfs/api/utils.py
https://github.com/python/asyncio/issues/258
> fix(app): adjust async for better usage and to account for asyncio bug

- rootfs/scheduler/mock.py
This adds a simple locking mechanism to ensure cache items are not overwriting one another when handling some of the bigger "global" lists
Should make Travis pass again consistently
> fix(mock): mock scheduler could not gracefully handle the concurrent deploy / scale

- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#342
http://www.django-rest-framework.org/topics/release-notes/#343
> chore(requirements): Django REST Framework 3.4.3

- .travis.yml
https://docs.travis-ci.com/user/caching/#Caches-and-build-matrices
> chore(travis): cache pip in travis runs

- rootfs/requirements.txt
- rootfs/scheduler/__init__.py
the yaml library needs to be compiled and that slows down CI
> ref(scheduler): remove yaml lib dependency

- rootfs/scheduler/__init__.py
> fix(scheduler): in scheduler::run check if pod state is an object or a string before acing on it

- rootfs/requirements.txt
http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): requests update to 2.11.0

- rootfs/requirements.txt
https://github.com/django-guardian/django-guardian/blob/devel/CHANGES
> chore(requirements): update to django-guardian 1.4.5

- rootfs/requirements.txt
https://github.com/litl/backoff/blob/master/CHANGELOG.md#v130---2016-08-08
> chore(requirements): update backoff 1.3.1

- rootfs/api/models/app.py
- rootfs/api/models/config.py
- rootfs/api/models/release.py
- rootfs/api/serializers.py
- rootfs/api/tests/test_healthchecks.py
- rootfs/scheduler/__init__.py
- rootfs/scheduler/tests/test_scheduler.py
> feat(healthcheck): Add support to create healthcheck per proctype

- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#344
> chore(requirements): Update Django REST Framework to 3.4.4

- .travis.yml
- Makefile
> ref(Makefile,.travis.yml): run shellcheck in container

- rootfs/requirements.txt
http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): update Requests to 2.11.1

- rootfs/scheduler/__init__.py
> ref(scheduler): _update_application_service had an unused name argument

- rootfs/api/models/app.py
- rootfs/api/models/appsettings.py
> ref(apps): move AppSettings scheduler logic to App model for simplicity

- rootfs/scheduler/__init__.py
This prevents RCs and Deployments fighting about pods when upgrading from v2.3 to v2.4 - An application is not migrated to Deployments until configuration / image / etc is udone
Fixes #995
> fix(scheduler): check if RC exists during a deploy before trying to use Deployments

- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#345
> chore(requirements): Update DRF to 3.4.5

- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
- rootfs/api/tests/test_build.py
- rootfs/scheduler/__init__.py
> fix(proctypes): update service after all the proctypes are deployed

- rootfs/api/models/release.py
- rootfs/scheduler/__init__.py
This one is very hard to write tests for so leaving that off for now.
Fixes #1002
> fix(release): during cleanup let pod deletion 404 in case Kubernetes cleaned up as well

- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#346
> chore(requirements): update DRF to 3.4.6

- CONTRIBUTING.md
> docs(CONTRIBUTING): update contributing doc

- rootfs/api/models/app.py
> fix(healthcheck): update healthchecks for non default process type

- rootfs/requirements.txt
https://docs.djangoproject.com/en/1.10/releases/1.10.1/
> chore(requirements): update to Django 1.10.1

- rootfs/api/models/tls.py
load and fetch service methods use morph package(https://github.com/metagriffin/morph) which flatten the dictionary.
we are adding ssl.enforce as another key and using morph to flatten the dict https://github.com/deis/controller/blob/master/rootfs/api/models/__init__.py#L92
```
morph.flatten({'domains': 'earthy-quilting', 'maintenance': 'false', 'ssl': {'enforce': 'False'}, 'ssl.enforce': 'True'})
{'ssl.enforce': 'False', 'domains': 'earthy-quilting', 'maintenance': 'false'}
```
> fix(tls): Update the value properly to work with morph

- rootfs/api/models/app.py
- rootfs/api/tests/test_build.py
> fix(procfile): route the traffic to web proctype always if its present in procfile

- rootfs/api/models/app.py
- rootfs/scheduler/__init__.py
Reduces duplication and discrepancy between each app mode, as has been seen in the past and can even be seen up till this change
As a side effect that will give run pods healthchecking - that can be undone if e2e is having any issues
> ref(app): centralise all application configuration handling in App model to be used by run, deploy and scale

- rootfs/requirements.txt
https://github.com/docker/docker-py/blob/master/docs/change_log.md#1103
> chore(requirements): update docker-py to 1.10.3

- rootfs/scheduler/mock.py
- rootfs/scheduler/resources/pod.py
- rootfs/scheduler/tests/test_pods.py
> chore(tests): improve Pod scheduler tests

- rootfs/requirements.txt
http://www.django-rest-framework.org/topics/release-notes/#347
> chore(requirements): update DRF to 3.4.7

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.10/releases/1.10.2/
> chore(requirements): update Django to 1.10.2

- rootfs/api/models/app.py
- rootfs/api/tests/test_app.py
> fix(app): an app can now be removed from the database even if the namespace for it was already deleted

- rootfs/requirements.txt
> chore(requirements): update pytz to 2016.7

- rootfs/api/serializers.py
- rootfs/api/tests/test_build.py
- rootfs/api/tests/test_pods.py
fixes part of https://github.com/deis/workflow-cli/issues/247
> fix(procfile): validate the proctypes during build itself

- rootfs/api/tests/test_hooks.py
- rootfs/api/tests/test_key.py
Related to https://github.com/deis/workflow-cli/pull/260, this PR adds SSH public key testing for ECDSA and ED25519.
> Add SSH pub key tests for ECDSA and ED25519 keys

- rootfs/requirements.txt
https://github.com/docker/docker-py/blob/release/docs/change_log.md#1104
> chore(requirements): update docker-py to 1.10.4

- charts/controller/templates/controller-deployment.yaml
- charts/controller/values.yaml
ref https://github.com/deis/charts/pull/373
> fix(registration): Add support to change the default regsitration mode

- rootfs/api/models/app.py
- rootfs/api/tests/test_build.py
> fix(release): Don't rollback if there is no build

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.10/releases/1.10.3/
> chore(requirements): update Django to 1.10.3

- rootfs/requirements.txt
See https://github.com/docker/docker-py/blob/release/docs/change_log.md#1106
Closes #1125.
> chore(requirements): update docker-py to 1.10.6

- rootfs/requirements.txt
See http://www.django-rest-framework.org/topics/release-notes/#352
> chore(requirements): update DRF to 3.5.2

- rootfs/api/serializers.py
- rootfs/api/tests/test_config.py
- rootfs/api/tests/test_limits.py
- rootfs/scheduler/resources/pod.py
- rootfs/scheduler/tests/test_pod_resources.py
Accept new cli format limits:set web=500m/2000m
Value is map to requests/limits parameter in Kubernetes resource management.
See https://github.com/deis/workflow/issues/562
e2e https://github.com/deis/workflow-e2e/pull/335
> feat(limits-cmd): accept new limits:set value type

- rootfs/requirements.txt
See http://www.django-rest-framework.org/topics/release-notes/#353
> chore(requirements): update DRF to 3.5.3

- rootfs/requirements.txt
See http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): update requests lib to 2.12.1

- rootfs/api/tests/test_auth.py
- rootfs/api/views.py
This ensures a 409 error is raised with the proper error to ensure the user knows why they cannot cancel the account. Beforehand it would show a 500 error because `django.db.models.deletion.ProtectedError` would be raised.
> fix(api): ensure a 409 is raised when cancelling a user with downstream objects

- rootfs/api/fixtures/tests.json
- rootfs/api/tests/test_app.py
- rootfs/api/tests/test_users.py
- rootfs/api/views.py
This gives the target user complete ownership over the releases, configuration and
other resources required when transferring an app's ownership.
closes #1126 
closes deis/deis#5019
> fix(api): transfer all downstream resources along with app

- rootfs/requirements.txt
See http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): update requests lib to 2.12.3

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.10/releases/1.10.4/
> chore(requirements): update Django to 1.10.4

- Makefile
- rootfs/api/admin.py
- rootfs/api/settings/testing.py
- rootfs/api/tests/__init__.py
- rootfs/dev_requirements.txt
See http://flake8.pycqa.org/en/latest/release-notes/index.html
> chore(dev_requirements): upgrade flake8 to 3.2.1

- rootfs/api/models/__init__.py
> fix(service-config): Don't add annotations if the value is empty

- README.md
The previous badge was tied to @helgi's VersionEye login.
> docs(README.md): update badge to use deis-bot's account

- rootfs/dev_requirements.txt
See https://coverage.readthedocs.io/en/coverage-4.3.1/changes.html#version-4-3-1-2016-12-28
> chore(dev_requirements): update coverage to 4.3.1

- rootfs/requirements.txt
See http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): update requests to 2.12.4

- rootfs/requirements.txt
See https://github.com/kjd/idna/blob/master/HISTORY.rst#22-2016-12-21
> chore(requirements): update idna to 2.2

- README.md
and link to main installation instructions.
> docs(README): remove helmc mention

- rootfs/api/settings/production.py
- rootfs/api/tests/test_auth.py
> fix(settings): disable LDAP by default

- rootfs/api/management/commands/healthchecks.py
This error message is useful even without debug enabled.
> fix(management): display error when connecting to the database

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.10/releases/1.10.5/
> chore(requirements): update Django to 1.10.5

- rootfs/requirements.txt
See http://docs.python-requests.org/en/latest/community/updates/#id1
> chore(requirements): update requests to 2.12.5

- rootfs/dev_requirements.txt
See https://coverage.readthedocs.io/en/coverage-4.3.4/changes.html#version-4-3-4-2017-01-17
> chore(dev_requirements): update coverage to 4.3.4

- rootfs/requirements.txt
See https://github.com/pyldap/pyldap/compare/pyldap-2.4.25.1...pyldap-2.4.28
> chore(requirements): update pyldap to 2.4.28

- Makefile
- README.md
> docs(README): update database usage in tests

- rootfs/requirements.txt
See https://github.com/jmespath/jmespath.py/blob/develop/CHANGELOG.rst#091
> chore(requirements): update jmespath to 0.9.1

- rootfs/requirements.txt
See https://github.com/litl/backoff/blob/master/CHANGELOG.md#v140---2017-02-05
> chore(requirements): update backoff library

- rootfs/requirements.txt
https://github.com/Julian/jsonschema/blob/master/CHANGELOG.rst#v260
> chore(requirements): update jsonschema library

- rootfs/dev_requirements.txt
See http://flake8.pycqa.org/en/latest/release-notes/3.3.0.html
> chore(dev_requirements): update flake8 linter library

- charts/controller/values.yaml
Refs deis/workflow#758 and deis/controller#950.
> fix(charts): default registration mode to "admin_only"

- rootfs/requirements.txt
See https://github.com/kjd/idna/blob/master/HISTORY.rst#24-2017-03-01
> chore(requirements): update idna to 2.4

- rootfs/requirements.txt
See http://pythonhosted.org/psycopg2/news.html#what-s-new-in-psycopg-2-7
> chore(requirements): update psycopg2 to 2.7

- rootfs/requirements.txt
See https://github.com/bradjasper/django-jsonfield/compare/1.0.3...2.0.0
> chore(requirements): update jsonfield to 2.0.0

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.10/releases/1.10.6/
> chore(requirements): update Django to 1.10.6

- rootfs/requirements.txt
See http://docs.gunicorn.org/en/stable/news.html#id1
> chore(requirements): update gunicorn to 19.7.0

- rootfs/requirements.txt
See https://github.com/kjd/idna/blob/master/HISTORY.rst#25-2017-03-07
> chore(requirements): update idna to 2.5

- rootfs/requirements.txt
See https://github.com/bradjasper/django-jsonfield/compare/2.0.0...2.0.1
> chore(requirements): update jsonfield to 2.0.1

- rootfs/requirements.txt
Fixes https://github.com/deis/controller/issues/1262 which is blocking all deis/controller ci builds.
> chore(rootfs/requirements.txt): add pyasn1

- rootfs/requirements.txt
See https://github.com/jmespath/jmespath.py/blob/develop/CHANGELOG.rst#092
> chore(requirements): update jmespath to 0.9.2

- rootfs/requirements.txt
See http://www.django-rest-framework.org/topics/3.6-announcement/#django-rest-framework-36
> chore(requirements): update djangorestframework to 3.6.2

- rootfs/requirements.txt
Minor bug fixes, see http://docs.gunicorn.org/en/stable/news.html#id1
> chore(requirements): update gunicorn to 19.7.1

- rootfs/requirements.txt
See https://github.com/django-guardian/django-guardian/compare/v1.4.6...v1.4.8
> chore(requirements): update django-guardian to v1.4.8

- rootfs/requirements.txt
See https://launchpad.net/pytz/+announcement/14547
> chore(requirements): update pytz to 2017.2

- README.md
This should have been included with #1271.
> docs(README): remove old testing prerequisites

- rootfs/dev_requirements.txt
See https://github.com/codecov/codecov-python/compare/v2.0.5...v2.0.9
> chore(dev_requirements): update codecov to v2.0.9

- rootfs/requirements.txt
See http://pythonhosted.org/django-auth-ldap/changes.html#v1-2-11-2017-04-22-testing-and-debugging-cleanup
> chore(requirements): update django-auth-ldap to v1.2.11

- rootfs/requirements.txt
See https://pyopenssl.readthedocs.io/en/latest/changelog.html#id1
> chore(requirements): update pyOpenSSL to v17.0.0

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.11/releases/1.11.1/
> chore(requirements): update Django to v1.11.1

- rootfs/requirements.txt
See https://www.django-rest-framework.org/topics/release-notes/#363
> chore(requirements): update DRF to v3.6.3

- rootfs/requirements.txt
See http://docs.python-requests.org/en/latest/community/updates/#release-history
and https://pypi.python.org/pypi/requests-toolbelt
> chore(requirements): update requests and requests-toolbelt

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.11/releases/1.11.2/
and https://github.com/jmespath/jmespath.py/blob/develop/CHANGELOG.rst#093
and https://github.com/litl/backoff/blob/master/CHANGELOG.md#v143---2017-05-22
and https://github.com/pyldap/pyldap/blob/master/CHANGES
> chore(requirements): update Django and supporting libraries

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.11/releases/1.11.3/
> chore(requirements): update Django to v1.11.3

- rootfs/dev_requirements.txt
- rootfs/requirements.txt
Lots of bug fixes in here--see each commit for the specific changelog.
> chore(requirements): update support libraries

- rootfs/requirements.txt
See https://docs.djangoproject.com/en/1.11/releases/1.11.4/
> chore(requirements): update Django to v1.11.4

- rootfs/dev_requirements.txt
See https://gitlab.com/pycqa/flake8/tags/3.4.1
> chore(dev_requirements): update flake8 to v3.4.1

- rootfs/requirements.txt
See https://www.django-rest-framework.org/topics/release-notes/#364
and https://django-auth-ldap.readthedocs.io/en/stable/changes.html#v1-2-15-2017-08-17-documentation-improvements
> chore(requirements): update DRF and django-auth-ldap
