.gitignore
Makefile
manifests/deis-workflow-rc.yml
rootfs/bin/boot

Changes the ReplicationController manifest to mount the Docker socket into the deis-workflow pod(s). ~~I think this works but today's update to k8s v1.1.1 is giving me fits in vagrant, so this is in-progress until I've done more testing.~~ Turns out there's a problem with volumes when a manifest didn't end in ".yml" This works for me now and lets `deis pull` get as far as pushing to the (nonexistent) repository.

feat(manifests): mount docker.sock in workflow pod

---

rootfs/api/models.py
rootfs/api/tests/test_app.py
rootfs/deis/settings.py
rootfs/requirements.txt
rootfs/scheduler/__init__.py
rootfs/scheduler/k8s.py

SSH_PRIVATE_KEY was something we relied on for the fleet scheduler.
We no longer require a ssh key so we can remove it. The same logic
applies for the --disable-swap option flag.

ref(controller): clean up scheduler code

---

rootfs/conf.d/confd_settings.toml

These should have been removed from the confd config in #10; this gets controller running again.

fix(confd_settings): remove old etcd dirs

---

.travis.yml

Travis CI's yaml validator pointed out this error in the addons: section. Also there was a typo in the vendor cache directive, and re-using Travis' canonical location for a python virtualenv seems to have backfired, so I moved it.

fix(.travis.yml): remove errant list dash

---

_scripts/ci/deploy.sh
docs/docs_requirements.txt
rootfs/registry/dockerclient.py
rootfs/requirements.txt

Marathon was used only by the mesos-marathon preview scheduler, and paramiko was used only by the fleet scheduler.

Remove unused marathon and paramiko libraries

---

rootfs/scheduler/k8s.py

Consolidate code and unify a bit more under single quote (as much of the code already is).
Rename raise_err to error to be clearer about its functionality
Clean up logic in _delete_pod and have waiting work in it.
More to come, split out to simplify review

ref(k8s): tidy up Python logic in k8s scheduler

---

Makefile
README.md
_scripts/ci/deploy.sh
docs/contributing/hacking.rst
docs/contributing/testing.rst

`deis/router` is doing it and seems more consistent with our naming policies

fix(make): use DEIS_REGISTRY as an env var for consisteny

---

docs/src/installing-deis/installing-the-deis-platform.md
docs/src/installing-deis/quickstart.md

docs(installing-deis): document installation process for alpha

---

.travis.yml
docs/Makefile

feat(travis): hook up docs to travis

---

rootfs/deis/settings.py

If you do not supply a host variable, Then psycopg2 will connect using a Unix socket in the same
manner as psql. Surprisingly, when you specify a HOST, psycopg2 will connect with TCP/IP, which
requires a password. This broke my environment with the following when running `make test-unit`:
OperationalError: fe_sendauth: no password supplied
See: http://stackoverflow.com/a/23871618

fix(settings): default to empty host environment variable

---

rootfs/build.sh

django-fsm used to need git installed to pull in a fork but the need for it was dropped https://github.com/deis/deis/commit/a6515c85e569859a2d6ce6b63e2e332f7b711e86

chore(build): remove git from image, no longer needed

---

rootfs/build.sh

`curl` is needed for the pip installation and came in via `git` before. 
https://pkgs.alpinelinux.org/package/main/x86_64/git depends on `curl`

fix(build): add curl again (came via git before) to install pip

---

rootfs/api/models.py
rootfs/api/south_migrations/0025_auto__chg_field_app_id.py
rootfs/scheduler/k8s.py

When we eventually allow applications to be grouped together in the same namespace, we'll want to
have the service names discoverable to other instances in the same namespace. Having a name like
"app-1234" was created so we could get over the limitation of 24 characters for service names. Now
that we're in v2, we can just restrict app names to 24 characters.
The app name validation regex was not changed because the docker repository name regex is a subset of the kubernetes service name regex, so we still need to keep ourselves restricted to that name regex so we can still push those images to the internal registry.
closes #17 
closes #32

fix(scheduler): use app name when creating services

---

rootfs/api/models/app.py

Looks like the image variable is needed used and thus we do not need docker lib in the App model

ref(models): remove docker.utils from app model as it is not needed

---

rootfs/scheduler/k8s.py
rootfs/templates/confd_settings.py

Accessing the k8s api by hostname fails sometimes from within the deis/workflow pod. This changes the `requests.Session` to use the IP address and port, which is more reliable, but at least for now requires disabling verification of the local SSL cert.
Cert verification is `False` here since the IP address in the request does match any of the hostnames in the server's cert, and neither that verification nor the HTTP `Host` header can be overridden in this case in the python requests library. That is, I couldn't see any way short of monkeypatching, after reading the requests source code and overriding several classes involved.

fix(k8s.py): access API server by IP address

---

manifests/deis-workflow-rc.yml
rootfs/api/tests/__init__.py
rootfs/api/tests/test_healthcheck.py
rootfs/api/views.py
rootfs/deis/urls.py

Rebases deis/deis#4457--thanks again @benwilber! Adds a matching Kubernetes [liveness probe](http://kubernetes.io/v1.1/docs/user-guide/production-pods.html#liveness-and-readiness-probes-aka-health-checks) to the ReplicationController manifest.

Controller healthcheck

---

rootfs/api/tests/__init__.py

logging.disable() refers to the maximum logging level you should *not* see. The current code hides even Critical
https://docs.python.org/2/library/logging.html#logging.disable

fix(tests): make tests show CRITICAL errors

---

rootfs/.coveragerc

Keep getting massive converge check on my `/usr/local/lib` global python pip install

fix(tests): exclude /usr/local/lib from converge report

---

.travis.yml
README.md

This change uses Travis CI's artifact feature to store build information
in S3. Specifically we'd like a client and a doc build so that we can test
and view changes for a specific build with these artifacts, as the rest of
the build artifacts are Docker images, uploaded to Quay.io and DockerHub.
We need to some new environment variables to the workflow job in order for this to work:
- ARTIFACTS_KEY
- ARTIFACTS_SECRET
- ARTIFACTS_BUCKET
- ARTIFACTS_S3_REGION
closes #61

feat(travis): upload docs and client to S3

---

rootfs/api/models.py
rootfs/api/tests/test_utils.py
rootfs/api/utils.py
rootfs/scheduler/k8s.py
rootfs/scheduler/mock.py
rootfs/scheduler/utils.py

Domain information is now saved to routerConfig annotations in addition to still being in etcd. This solves part of #50
Also adds new flatten and dict_merge to both scheduler and models
The code has a little oddity in it where subdomains for app (on the platform domain) are added during scale event from 0 to 1. That will be address in #88
Also note that the Domain model reaches into what previously was consider a protected function (get / update services)
It is possible to remove the apps subdomain but during any scaling event it gets added back to the Domain model. This allows the router to treat all domains the same way

ref(models): add domains to k8s data for router to use

---

_tests/tests_suite_test.go

The `AfterSuite` cleanup was raising an error because these func parameters were incorrect.

fix(_tests): correct parameters for account cancel

---

rootfs/api/models.py
rootfs/api/views.py

When debugging #95, there was a case where the `except` handler failed since `new_release` hadn't been defined yet in the preceding `try` block. This guards against that potential problem in the three similar cases I could find.

fix(api): delete new_release only if it exists

---

_tests/users_test.go

A very minor fix to `users_test.go` that removes a TODO. Tested interactively with ginkgo's awesome [focus](https://onsi.github.io/ginkgo/#focused-specs) feature.

fix(_tests): add admin user check tests

---

_tests/perms_test.go

The remaining TODO: items depend on an application being deployed, which ideally would have been done once already in BeforeSuite. I'll work on that bit next, as it is required by many other test cases.

tests(perms): implement half of permissions tests

---

docs/src/installing-deis/installing-the-deis-platform.md

Many, many apologies... this is a rewrite of doc that @technosophos added just this morning.  After seeing @sgoings stumble over a few issues, I realized the docs had to be a bit more descriptive in terms of the possible paths on can take to set this up (or may be forced to take, depending on the capabilities of their cluster and underlying infrastructure).
Essentially, this now documents three paths:
1.  Running where the "cloud provider" was able to provision an external load balancer connected to the router service.
2. Running where the above is _not_ true, but you are still able to provision your own load balancer.
3. Where 1 and 2 both don't work... i.e. Vagrant.
Don't anyone be shy about feedback on this PR.  These changes are extensive and I want to be super certain that the …

doc(routing/ingress): improve docs

---

.gitignore
.travis.yml
Makefile
_scripts/ci/bintray-template.json

Travis artifacts is great for creating builds and uploading to S3,
but one thing it misses on is the ability to grab the "latest" build
(as seen in the README). In order for a user to grab the latest
client build, he or she must know the latest Travis build that went
green and download the client using that URL.
Seth Goings fronted the work with releasing the helm client on
bintray, which so far has been a great success. This PR moves us
over to bintray for that one-liner `(curl https://... | sh)` special
sauce.
refs #94. Still need to update docs with the first uploaded release
after this PR is merged in order to close it.

feat(travis): deploy client builds to bintray

---

.travis.yml

Travis' `on` condition is an AND operation, so essentially in its
current configuration no client builds will be produced because
the build must be
1) from a merge to master AND
2) a tagged release
We have branching logic in `make prep-bintray-manifest` that will
deploy client builds to either deisci or to the deis org depending
on if the commit is from a tag or not, so we should deploy on
every PR so the deisci org is filled to the brim with cilent builds.

fix(travis): deploy client on every push to master

---

manifests/deis-workflow-rc.yml
rootfs/scheduler/k8s.py

mounted secret volumes in workflow and slugrunner template.
creates a new secret minio user in app namespace by reading files from mounts.
Creates namespace, services and Secrets first and then RC.
requires https://github.com/deis/slugrunner/pull/5
Todo// decide whether to read secret from api server or mount secrets to workflow ?
Todo// default port is 5000. Need a way to specify ports 
if you are testing using helm dont forget to add volume mounts for deis-workflow-rc.yaml in your helm workspace.
Added by Aaron on 12/18/2015 to auto close issues:
Fixes https://github.com/deis/slugrunner/issues/6

feat(secrets): add support for deis minio secrets

---

_scripts/ci/bintray-template.json

The uploadPattern is a required field that specifies the upload path
on Bintray.
fixes #144

fix(bintray): add uploadPattern to bintray json

---

_tests/tests_suite_test.go

Removes the `example-go` app that was accidentally checked in to version control. Also stops checking for optional `DEIS_WORKFLOW_SERVICE_PORT` and doesn't hard-code the location of the `deis` CLI.

Small test fixes

---

docs/src/contributing/triaging-issues.md
docs/src/roadmap/release-checklist.md
docs/src/understanding-deis/architecture.md
docs/src/understanding-deis/components.md

Partially addresses #161 
The documentation requires a comprehensive overhaul, but to keep PRs reasonable in scope, I'm limiting this to simple removal of references to a component that no longer exists.  A series of PRs such as this will incrementally address #161.

doc(*): strike references to logspout

---

docs/src/installing-deis/installing-the-deis-platform.md

Fixes #149
I had to move more text around than I would have liked here. The major change is introducing the edit step before `helm install`, which required me to explain (as minimally as I could) what the platform domain should be.
I'd like suggestions particularly on how to improve that text. Restructuring suggestions are also welcome.
cc/ @technosophos @krancour

doc(installing-the-deis-platform.md): change instructions to edit router RC manifest before helm install

---

docs/src/contributing/triaging-issues.md
docs/src/installing-deis/system-requirements.md
docs/src/roadmap/release-checklist.md
docs/src/roadmap/roadmap.md
docs/src/using-deis/managing-an-application.md

doc(*): strike references to schedulers that aren't k8s

---

docs/src/contributing/submitting-a-pull-request.md
docs/src/contributing/testing.md
docs/src/contributing/triaging-issues.md
docs/src/roadmap/release-checklist.md
docs/src/understanding-deis/architecture.md
docs/src/understanding-deis/components.md

Another PR that partially addresses #161 
Logger is neither included in nor a dependency of workflow ATM.  It's an add-on that requires a specially configured k8s cluster.

doc(*): strike references to logger

---

docs/src/contributing/community.md

These are very minor updates to bring the community.md up to snuff.  Mainly the page has been editing to acknowledge that Deis software spans numerous repositories.

doc(community): update community docs

---

README.md
docs/src/using-deis/installing-the-client.md

`set -o pipefail` is an illegal option for /bin/sh. switch to /bin/bash

fix(docs): hotfix oneliner

---

manifests/deis-workflow-rc.yml

Adds a k8s [readiness check](http://kubernetes.io/v1.1/docs/user-guide/production-pods.html#liveness-and-readiness-probes-aka-health-checks) to workflow, in addition to the existing liveness check.

feat(manifests): add k8s readiness check

---

docs/src/contributing/development-environment.md

This is a massive rewrite of the docs for setting up the development environment.
Note, I expect these to shrink significantly as we make more headway in transitioning each component's development environment to something container-based.  For now, this is necessary...
This does away with mentions of defunct things like `make dev-cluster` and `deisctl` and replaces them with information about building and deploying to k8s.
This massive update also re-orders docs a bit and pays down some outstanding inaccuracies.
Please note that this doc tries really hard to document the _general_ procedures for hacking on each of our _many_ components.  Until we have made our Makefiles uniform, your mileage from these instructions may vary from one component to the next.  I don't see this as a flaw in …

doc(dev-env): update dev env docs

---

docs/src/contributing/testing.md

Partially addresses #185 and updates docs to reflect that testing procedures have changed-- notably that integration tests spanning multiple Deis components have moved to their own repository.
Note that the mileage you get from this doc many vary.  Probably not all of our components currently implement the `test-style`, `test-unit`, and `test-functional` make targets.  I do not see this as a flaw in the documentation.  I think the documentation sets a standard for the components to aspire to-- and they will once @sgoings has applied some [makeup](https://github.com/sgoings/makeup).

doc(testing): Update testing docs

---

CONTRIBUTING.md
docs/mkdocs.yml
docs/src/contributing/submitting-a-pull-request.md
docs/src/troubleshooting/troubleshooting.md

Partially addresses both #161 and #185 
`contributing.md` was a bit stale.  It needed updates to reference additional support channels (multiple issue queues for individually repo'ed Deis components).  While editing, I noticed tremendous overlap with other documentation in `docs/src/contriubting`, so I simplified `contributing.md` to be a quicker read that references the more detailed docs where applicable.

doc(contributing): update contributing.md

---

rootfs/api/models.py

Previously this was used by publisher for healthchecks and also the router for app level IP/CIDR whitelisting
Going to use #205 to start addressing the latter

ref(models): remove config interaction with Config model

---

_tests/tests_suite_test.go

This patch makes the code in `AfterSuite` attempt to delete both users, even if the first fails. Combined with https://github.com/deis/workflow/pull/191, this will at least help with error reporting and graceful cleanup
cc/ @lanej @michelleN

fix(tests_suite_test.go): cancel accounts gracefully in the AfterSuite block

---

_tests/tests_suite_test.go

not strictly necessary for `v2.0-alpha1`, but the additional randomness would help with concurrent test runs on the same deis cluster

fix(tests_suite_test.go): seed the rng, use true random numbers for users, passwords and emails

---

rootfs/build.sh
rootfs/deis/settings.py
rootfs/requirements.txt
rootfs/templates/confd_settings.py

LDAP poses a problem with the upgrade path to Django 1.9 as the modules involved are not compatible.
Removing until we have a better identity and federation story. And the django plugin works again
Ref #207

ref(ldap): remove LDAP temporarily

---

client/controller/client/http.go

Tested via `mitmproxy` and:
```console
client [client-proxy]$ http_proxy=localhost:8080 ./deis ps -a rococo-vocalist
=== rococo-vocalist Processes
--- web:
web.1 up (v2)
web.2 up (v2)
web.3 up (v2)
web.4 up (v2)
web.5 up (v2)
```

bug(client): restore client proxy behavior

---

rootfs/api/fields.py
rootfs/api/migrations/0002_auto_20151215_0352.py
rootfs/api/models.py
rootfs/api/tests/__init__.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_hooks.py
rootfs/api/urls.py
rootfs/api/views.py
rootfs/bin/boot
rootfs/deis/settings.py
rootfs/deis/urls.py
rootfs/requirements.txt
rootfs/setup.cfg

https://docs.djangoproject.com/en/1.8/releases/1.8/
Notable changes:
* Moved us to using the official `UUIDField` - The oddity with this one is the returned value is a `UUID` object so it need to be based to string if any `substring` or similar operation is performed
* Updated all libraries
* TestCase http client seems to be returning values differently than it used to. `OrderedDict` straight up without `results` or `count` on the top level
* templating changed in 1.8 to support multiple engines. https://docs.djangoproject.com/en/1.8/ref/templates/upgrading/ on how it all changed
* django.conf.urls.patterns is deprecated in 1.8 and removed in 1.10 https://docs.djangoproject.com/en/dev/releases/1.8/#django-conf-urls-patterns
Note: `django_auth_ldap` is disabled since it causes a migration …

feat(*): update django from 1.7 to 1.8

---

rootfs/deis/context_processors.py
rootfs/deis/settings.py
rootfs/requirements.txt

Notable changes:
* ditch deis context_processor for https://docs.djangoproject.com/en/1.9/ref/contrib/sites/#site-middleware
* `registry` no longer treated as an app as it was causing AppRegistry prepared problems
* django-json-field swapped out for jsonfield for django 1.9 compatibility

feat(*): update django from 1.8 to 1.9

---

manifests/deis-workflow-service.yml

Unlike the one in the deis helm chart, the service manifest for workflow included here describes a service that's unroutable.  This causes havoc for anyone using the router-- i.e. anyone who started from a stock helm install of Deis and now wants to hack on workflow and sideload their hacks into their existing cluster.  Making the service routable also causes no harm to anyone _not_ wishing to use the router.

feat(manifests): Make the workflow service routable

---

rootfs/api/serializers.py
rootfs/api/tests/test_release.py

Hack got added in deis/deis#2898 but is no longer needed since we use native UUIDField and DRF has been updated to 3.3
Depends on #109

ref(api): Remove a DRF hack around UUID and UniqueTogether

---

client/controller/api/apps.go
client/controller/models/apps/apps.go
client/controller/models/apps/apps_test.go
rootfs/api/models.py
rootfs/api/serializers.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_hooks.py
rootfs/api/views.py
rootfs/bin/boot
rootfs/deis/settings.py
rootfs/templates/confd_settings.py

Addresses the workflow side of #111 but doesn't do the client part so that it opens up the right domain

ref(*): remove the notion of a platform domain known to workflow

---

rootfs/api/serializers.py
rootfs/deis/settings.py

With `JSONField` I couldn't have it do `binary` in but not out, which is how the original json serializer we have works.

ref(serializer): based json serializer on the DRF 3.3 JSONField and set global DRF DateTime

---

client/controller/models/apps/apps.go

Fixes #111 for the average case where the controller URL begins with `deis.`.
Other edge cases are unaccounted for, but there's really no good way to accurately and _universally_ infer application URLs based on the controller URL since the controller URL really could be anything in v2.

fix(client): fix URLs used by deis open

---

docs/src/using-deis/configuring-an-application.md
rootfs/api/models.py
rootfs/api/tests/test_config.py
rootfs/scheduler/__init__.py

Use k8s liveness and readiness probes (HTTP GET only for now) to replace the defunct publisher healthcheck system. For now those two are conflated into one to support the current documented deis healthcheck workflow and an assumption of port 80 is in the code, as well as HTTP (no ssl).
All healthcheck related tests were axed as they are no longer applicable and in fact not possible to test until there is a more robust k8s testing strategy for workflow.
http://kubernetes.io/v1.1/docs/user-guide/pod-states.html#container-probes has more information on what probes can do and what's available
Fixes #76

feat(healthcheck): use k8s liveness and readiness probes for app healthchecks

---

rootfs/api/models.py
rootfs/registry/dockerclient.py
rootfs/registry/tests.py

I am assuming we need to keep the `FROM` portion of the `build` section? We can not just pull the source and push to our own registry with a new name?
ref #13

feat(registry): stop adding last mile ENV Vars into slugs as k8s handles that

---

rootfs/bin/boot

Slows down boot time and as such the development cycle. Removing only because we have plans to fully remove etcd and it's already mostly been ripped out

ref(etcd): remove etcd sleep at boot

---

rootfs/bin/boot
rootfs/scheduler/__init__.py
rootfs/templates/confd_settings.py

Not the biggest fan of reading it on every API request but we do have a very low yield API right now and we can somewhat rely on filesystem caches
Maybe later (stable timeframe or after stable) I can output it into the file statically or use confd + env vars like I did in #245 for other things
Fixes #9

ref(secrets): read generated secrets from k8s for the setings file

---

rootfs/requirements.txt

See https://docs.djangoproject.com/en/1.9/releases/1.9.1/. I tested with the workflow-e2e tests against the deis-dev `helm` chart.

chore(requirements.txt): update Django to 1.9.1

---

rootfs/api/models.py
rootfs/api/views.py
rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

Implement deis tags as k8s nodeSelector. Uses the /nodes API endpoint to verify if a label already exists or not. Multiple labels compound.
This is the first implementation of labelSelector and fieldSelector on a GET call. It will be ported to most of the GET functions eventually
Depends on #260
Fixes #168

feat(tags): implement tags as k8s node selectors

---

rootfs/api/models.py

In python 3 requests returns `bytes` - turns out the logger testing is very veryyyyy mocked out and doesn't actually behave normally. Potentially should look at mocking out the logger GET request instead of the `/apps/<app>/logs` one
Confirmed with @jchauncey that this works
Fixes #265

fix(logger): requests object returns bytes from logger, convert to string

---

rootfs/api/tests/__init__.py

https://docs.djangoproject.com/en/1.7/topics/testing/overview/
When you run your tests, the default behavior of the test utility is to find all the test cases (that is, subclasses of unittest.TestCase) in any file whose name begins with test, automatically build a test suite out of those test cases, and run that suite.

ref(tests): since Django 1.7 tests are auto detected based on test*.py

---

manifests/deis-workflow-rc.yml
rootfs/api/tests/test_healthcheck.py
rootfs/deis/urls.py

`/healthz` is a more standard endpoint name for k8s healthchecks. See also deis/charts#76.

ref(healthchecks): rename endpoint to /healthz

---

rootfs/scheduler/__init__.py

This is related to the error in #297 where one value was a number
```
}, {
"name": "DOCKERIMAGE",
"value": "1"
}, {
"name": "NODE_ENV",
"value": "production"
}, {
"name": "REDIS_PORT",
"value": 6381
}, {
"name": "REDIS_HOST",
"value": "192.168.2.2"
}],
```

ref(workflow): the value of any key in env must be a string

---

docs/requirements.txt

Adds official support for Python 3.5, among other things.
See http://www.mkdocs.org/about/release-notes/#version-0150-2016-01-21
I've tested this locally with Mac OS X python 3.5.1 from Homebrew.

chore(requirements.txt): update mkdocs to 0.15.0

---

rootfs/requirements.txt

See https://raw.githubusercontent.com/django-guardian/django-guardian/devel/CHANGES. In particular, django-guardian/django-guardian#366 was fixed which seems possible to occur in Deis' PostgreSQL setup at first glance.
I tested this with the deis-dev chart on [kube-solo-osx](https://github.com/TheNewNormal/kube-solo-osx).

chore(requirements.txt): update django-guardian to 1.4.1

---

rootfs/templates/confd_settings.py

Relates to deis/builder#116
This only helps if we are reading it from the files, in future versions we'll get those values directly via ENV and we may not be able to strip it ahead of time.
/cc @aledbf @arschles

fix(secrets): strip whitespaces / newlines from k8s secrets when reading the files

---

docs/mkdocs.yml

Some JS files required for the right-hand nav bar weren't being loaded, so top-level `l1` nav was failing.
TESTING: install the python `docs/requirements.txt` using Python 3.5, then `cd docs/ && make build && mkdocs serve`. Then open a browser to http://127.0.0.1:8000/ and enjoy a functional right-hand navigation bar.

fix(docs): use extra_javascript to fix navigation

---

rootfs/deis/settings.py

Only one django site is used so we do not need the site framework (https://docs.djangoproject.com/en/1.9/ref/contrib/sites/)

chore(django): remove the use of site framework

---

client/deis.go
client/parser/version.go

This feature flips docopt-go's version parsing logic switch off
in favour of our own in-house version parsing lib. This has the
following side-benefits, all of which are valid commands:
- `deis -v`
- `deis version`
- `deis help version`
ported from deis/deis#4895

feat(client): document deis version

---

Makefile
rootfs/api/management/commands/healthchecks.py
rootfs/api/views.py
rootfs/bin/boot

On boot see if the DB is connectable *before* hitting the migration step and in `/healthz` connect to the DB and run a simple dumb `SELECT` statement
Note that this will cause k8s to restart the container after a few tries, if the DB is not available then it will go into a crash loop. This is the nature of the beast:
http://kubernetes.io/v1.1/docs/user-guide/production-pods.html#liveness-and-readiness-probes-aka-health-checks and http://kubernetes.io/v1.1/docs/user-guide/walkthrough/k8s201.html#health-checking
> if the Kubelet discovers a failure the container is restarted.
This is is also based on the [Restart Policy](http://kubernetes.io/v1.1/docs/user-guide/pod-states.html#restartpolicy), which we currently define as `Always
To test deploy `deis-workflow` RC and then scale …

feat(healthchecks): add DB health check to /healthz

---

rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_key.py
rootfs/api/urls.py
rootfs/api/views.py

Give builder the ability to query for application or application + user and get the public key associated if both resource exist.
Replaces etcd usage for builder.
Fixes #335

feat(builder hooks): app and user hooks for builder to get public keys

---

rootfs/api/tests/test_users.py
rootfs/api/urls.py

This ports the fix from deis/deis#4898 to Deis v2 workflow. 
I updated the URL to `/v2/` here relative to the original PR.  Thanks again to @smt116, let me know if you have any concerns or comments.
Closes #333.

fix(controller): do not require slash at the end of `GET /v2/users`

---

client/Makefile

I am a big fan of #340 (because I am a fan in general of containerizing our builds), but it had the unfortunate side-effect of removing any possibility of building the client from source on a Mac and then _using_ that client on a Mac-- this is something I do frequently and I suspect I'm not the only one.
This PR restores that possibility through:
```
$ make binary-build install
```

fix(Makefile): Restore local build/install capability

---

rootfs/scheduler/__init__.py

Without some info about the error is not possible to know where to look
Example without the log:
```
ERROR srv-f22: srv-f22_v1046.web (deploy): failed to create ReplicationController "srv-f22-v1046-web" in Namespace "srv-f22": 400 Bad Request
{'apiVersion': 'v1', 'metadata': {}, 'kind': 'Status', 'status': 'Failure', 'message': 'ReplicationController in version v1 cannot be handled as a ReplicationController: [pos 1053]: json: expect char \'"\' but got char \'6\'', 'code': 400, 'reason': 'BadRequest'}
```

feat(workflow): log the template used in case of an error

---

rootfs/scheduler/__init__.py

chore(scheduler): remove second param in get() call as it is redundant

---

client/cmd/config.go
client/parser/config.go

This was briefly discussed as a V2 thing in deis/deis#4675 and deis/deis#4697.
I personally like it cause it's more unixy, but I understand if this is rejected because this is really a personal preference thing :smiley:.
If there is interest I will make the same change for `config:pull`.

feat(client): use unix pipes with config:push

---

client/controller/models/apps/apps.go

fixes #267
This fix provides a better error message when an error code or len(body) < 1 is returned from the workflow api.

fix(logger): Try not to fail so hard when issuing deis logs command

---

rootfs/Dockerfile
rootfs/api/management/commands/load_db_state_to_k8s.py
rootfs/api/models/__init__.py
rootfs/bin/boot
rootfs/deis/settings.py
rootfs/requirements.txt
rootfs/templates/confd_settings.py

This switches `confd` to source in `env` var for `gunicorn` and a few other minor things, for now
Following items need to be figured out and #9 touches on some of that
Depends on #242 as it ditches one of the `etcd` requirement that is embedded in the models

ref(*): remove etcd now that all state is being handled by db/k8s

---

client/Makefile

VERSION was previously being defined in multiple Makefiles.
This change creates includes.mk to store the canonical version
for this and other values.

feat(Makefile): organize Makefiles to simplify/unify VERSION

---

rootfs/conf.d/local_settings.toml
rootfs/deis/settings.py
rootfs/templates/local_settings.py

This fix renames and moves confd_settings.py to local_settings.py
within the container. This allows us to import the generic settings.py
and overwrite existing values, allowing the database settings to be
overwritten.

fix(local_settings.py): read DATABASES from settings.py

---

rootfs/templates/local_settings.py

deis/postgres now creates the database name from the username.
See https://github.com/deis/postgres/blob/master/rootfs/docker-entrypoint.sh#L62

fix(local_settings): infer database name from username

---

client/cmd/auth.go
client/controller/models/auth/auth_test.go
rootfs/api/tests/test_auth.py
rootfs/api/views.py

```
deis auth:cancel --username=slack
cancel account slack at http://deis.172.17.8.100.xip.io? (y/N): y
Error:
409 Conflict
detail: slack still has applications assigned. Delete or transfer ownership
```
Can't do anything about the `Error` info there until we refactor the client

fix(auth): return a 409 if a user is cancelled that has apps

---

client/controller/models/apps/apps.go

fixes #401
Create a user friendly error message and return that instead of a string.

fix(logger): Return non-zero exit code when deis logs fails

---

client/cmd/config.go
client/cmd/config_test.go

fix(client): exit 1 with malformed config:set input

---

client/pkg/git/git.go

When doing any `deis apps:` command, the CLI would fail to detect the app name from the `git` remote if the workflow controller URL includes a port. The `findRemote` function was searching for "deis.192.168.64.2.xip.io:31713" (for example) in output like this:
```console
$ git remote -v
deis	ssh://git@deis.192.168.64.2.xip.io:2222/blurry-doghouse.git (fetch)
deis	ssh://git@deis.192.168.64.2.xip.io:2222/blurry-doghouse.git (push)
origin	https://github.com/deis/example-go (fetch)
origin	https://github.com/mboersma/example-go (push)
```
Closes #419. See also #280.

fix(git): strip controller port when parsing git remotes

---

rootfs/scheduler/__init__.py
rootfs/scheduler/states.py

New states are
- starting
- terminating
These are the following main states that encompass a Pod in phase Running
k8s `state[Phase] == 'Running'` but container states are still not ready (probes and status itself on the container)
k8s `state[Phase] == 'Running'` but container states are ready and container status is "running"
k8s `state[Phase] == 'Running'` but container states are not ready (due to termination) and container status is "terminating"
Fixes #430

fix(scale): add more state information to make scale smarter

---

rootfs/scheduler/__init__.py

I can not spot where it is used. Potentially it got accidentally refactored out but can't see where that would be

ref(scheduler): logs in scheduler does not appear to be used anymore

---

rootfs/dev_requirements.txt

Pins the python `coverage` tool at 4.0.3 and updates `flake8` to 2.5.4.
See https://gitlab.com/pycqa/flake8/blob/master/CHANGES.rst

chore(dev_reqs): pin coverage and update flake8

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

This offers more granularity when catching exceptions and if the HTTP version comes down the user will know there is a response class variable

ref(scheduler): spin off response info in KubeException into KubeHTTPException

---

rootfs/requirements.txt

OpenSSL 1.0.2g introduces some CVE fixes but also broke basic APIs and that broke pypi cryptography. We can not pin to a lower openssl on Alpine either

fix(requirements): pull in the the fix branch of cryptography until official release happens

---

rootfs/api/tests/test_domain.py
rootfs/api/views.py

Affects trying to remove certificates, domains and other items via DELETE or updating via POST / PUT
Fixes #440

fix(views): return a 404 when trying to query on an object that does not exist

---

client/controller/client/http.go
client/controller/client/http_test.go
rootfs/deis/settings.py

Moved us to using limit instead of page_size so we didn't have to subclass things
http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination
Fixes #463

fix(pagination): use the proper limit pagination style from DRF

---

client/Makefile

In #456 with a slight re-arrangement in client's Makefile, `go build`, being container-ized, was defaulting to producing a linux binary.  We now need to pass in host OS for building on darwin cc @mboersma

fix(make): determine host OS for supplying to (container-ized) go build

---

client/cmd/certs.go

...instead of ignoring and reporting misleading affirmation.  Will be covered in e2e certs_test(s)...
So instead of this:
```
$ deis certs:attach foo goo
Attaching certificate foo to domain goo... done
```
We will currently get this:
```
$ deis certs:attach foo goo
Attaching certificate foo to domain goo... Error:
404 Not Found
detail: Not found.
```
(Where `foo` is not a valid cert and/or `goo` is not a valid domain)
Closes #462

fix(certs): propogate err in certs:attach/detach/remove

---

client/Makefile

Due to https://github.com/mitchellh/gox/issues/50, if GOOS is set to particular OS,
gox will build all 'cross-compiled' binaries for that GOOS.
Fixes #468

fix(client/Makefile): don't export GOOS when running gox

---

Makefile
rootfs/api/models/app.py
rootfs/api/tests/test_domain.py
rootfs/scheduler/__init__.py
rootfs/scheduler/abstract.py
rootfs/scheduler/chaos.py
rootfs/scheduler/mock.py

This modifies things so that k8s resources are created during app creation, allowing Domains and other resources to be added on at any point, even before a deploy.
Changes the world a little bit around if a scale vs deploy internally is called on first deploy (as it was before)
Technically this change brings in the ability to change the target port based on a deploy but that's just a by product
Fixes #420

ref(scheduler): create base k8s resources on app creation and update them during deploy

---

rootfs/api/models/container.py
rootfs/scheduler/__init__.py
rootfs/scheduler/abstract.py
rootfs/scheduler/chaos.py
rootfs/scheduler/mock.py

fix(scheduler): set env, limits, tags for run containers

---

client/cmd/apps.go

Go's net/url package returns malformed urls when a port is specified to `url.Parse()`.
For example, given "kiddie-armchair.192.168.64.2.xip.io:31258", `deis open` would call this `AppOpen` func and open a browser to "http:31258". The code appears to intend just to ensure a URL scheme prefix, so string manipulation should be adequate.

fix(cmd/apps): simplify URL prefixing

---

rootfs/scheduler/__init__.py

The `requests` library was defaulting to ISO-8859-1 when decoding the k8s pod GET request, which could mangle the output from `deis run`. Explicitly [setting the encoding](http://docs.python-requests.org/en/master/user/quickstart/#response-content) fixes this.
It didn't appear to be worthwhile writing this behavior into the mock scheduler for a unit test (although please do talk me out of that rationalization), but this will be covered by [a spec in config_test.go](https://github.com/deis/workflow-e2e/blob/master/tests/config_test.go#L148) once that is enabled.
Closes #478.

fix(scheduler): handle pod log response as utf-8

---

rootfs/api/models/app.py
rootfs/api/views.py
rootfs/scheduler/__init__.py

gunicorn reload will fix things up, as will a deploy and scale operation.
Test steps:
* Start an app
* Delete the `minio-user secret`, `service` or `namespace*
* verify that the k8s resource is gone
* restart `deis-workflow` or trigger a deploy or run a scale operation
* verify that the k8s resource is back
Example of an app created, service is deleted, the workflow pod deleted (for cycling of gunicorn and such) and then verify that service is back
```
workflow  (fix_app_save>) $ deis create --no-remote
Creating Application... done, created dainty-headwind
remote available at ssh://git@deis.micro-kube.io:2222/dainty-headwind.git
workflow  (fix_app_save>) $ k get svc --namespace dainty-headwind
NAME              CLUSTER_IP   EXTERNAL_IP   PORT(S)   SELECTOR …
```

fix(k8s): recreate basic k8s resource required for apps if they are missing

---

rootfs/api/serializers.py
rootfs/api/tests/test_config.py

See https://github.com/kubernetes/kubernetes/blob/release-1.1/docs/user-guide/labels.md#syntax-and-character-set for an explanation of what is legal in a k8s label key and value. Previously Deis was disallowing the slash `/` character which could denote a DNS-style prefix for a label key.
See also deis/workflow-e2e#67, which this unblocks.

fix(serializers): validate tags properly as k8s labels

---

.travis.yml
Makefile

Many things are included by default when using python as the language (https://docs.travis-ci.com/user/languages/python)
Removing caching since we are in sudo mode so no caching is happning but also the pip directory is already cache if we are on the container based infrastructure (https://docs.travis-ci.com/user/caching/#pip-cache)

chore(travis): move travis to Python only testing

---

rootfs/api/models/certificate.py

The logic was just plain wrong in the original PR (#492)
Fixes #498 
/cc @krancour @vdice

fix(certificates): make sure domains are 0 for a cert before removing the secret

---

README.md

After `deis/workflow` was changed to `deis/controller`, the badge images and links broke
cc/ @bacongobbler

chore(README.md): update badges to point to controller

---

.travis.yml

The job name at https://ci.deis.io has been changed to
controller-master, so travis needs to be updated to push to that
job.

fix(travis): update secure URL

---

rootfs/scheduler/__init__.py

For now fetch the minio credentials from the API
ref #458
ref #521
Note: I can change it to to object-storage if someone points me to the doc what to use instead

ref(scheduler): fetch object storage credentials from API instead of local secret

---

Makefile

The `--parallel` flag speeds up the overall unit test suite, but at the cost of CPU usage and code coverage reports.
```console
$ TEST_PROCS=6 make test-unit-quick
cd rootfs \
&& ./manage.py test --noinput --parallel 6 --noinput registry api
Creating test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
.................................................................................................................................................................
----------------------------------------------------------------------
Ran 161 …
```

feat(Makefile): add test-unit-quick target

---

rootfs/build.sh

The bootscript now uses an internal pip which then bootstraps from pypi

chore(pip): update pip to 8.1.1 and use the new bootscript

---

rootfs/api/tests/__init__.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py

They are not needed now that scheduler uses a request mock in the background

chore(tests): remove various redundant python-request mocks

---

rootfs/api/views.py
rootfs/bin/boot

boot script and friends worked just fine because the settings were passed to it but wsgi.py auto uses settings.py if nothing else is passed in

fix(boot): make wsgi aware of what settings file to use (production)

---

Makefile

When contrib scripts were moved to _scripts this didn't get updated.
Now that we have many deis repositories however, it may more sense to remove this from here and instead move it to the documentation.

fix(Makefile): fix commit-msg task

---

rootfs/api/tests/test_api_middleware.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_auth.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_certificate.py
rootfs/api/tests/test_certificate_use_case_1.py
rootfs/api/tests/test_certificate_use_case_2.py
rootfs/api/tests/test_certificate_use_case_3.py
rootfs/api/tests/test_certificate_use_case_4.py
rootfs/api/tests/test_certificate_use_case_5.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_domain.py
rootfs/api/tests/test_healthcheck.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_key.py
rootfs/api/tests/test_perm.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py
rootfs/api/tests/test_users.py

Simplifies many calls
By setting a default DRF testing format (was already done in the settings file anyway), moving to using APITestCase and friends, plus credentials / login then the tests overall look cleaner and in many cases easier to grok
More information is at http://www.django-rest-framework.org/api-guide/testing/
Note that there is no need to use `json.dumps` when sending data as DRF takes care of that

ref(tests): move to using the TestCase classes DRF provides

---

rootfs/scheduler/__init__.py

The problem here is that multiple process types will let the *last* process type win out. Instead let the first one win

fix(scheduler): only update application service definition once

---

rootfs/dev_requirements.txt

After running unit tests many times, I eventually hit an error and found the `make test-unit-quick` version needs a support library in order to pickle (serialize) python traceback objects:
```console
$ make test-unit-quick
cd rootfs \
&& ./manage.py test --noinput --parallel 4 --noinput registry api
Creating test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
Cloning test database for alias 'default'...
test_certficate_denied_requests (api.tests.test_certificate.CertificateTest) failed:
FileNotFoundError(2, 'No such file or directory')
Unfortunately, tracebacks cannot be pickled, making it impossible for the
parallel test runner to handle this exception cleanly.
In order …
```

fix(dev_requirements): add tblib for multiprocessing tracebacks

---

rootfs/api/models/app.py
rootfs/api/tests/__init__.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py
rootfs/deis/settings.py
rootfs/deis/testing.py
rootfs/dev_requirements.txt
rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

Hits the router IP via python-requests with a Host header (uses nip.io) to emulate a request to the application. Sends a Deis Controller UA to make debugging easier
HTTP mocking is required for this to work in tests and all tests now get peppered with mock_requests object, which they can use for other purposes as well if required
Depends on a change to the requests_mock python package for testing only, pulling that from git currently
Tests take 2x the time because of added timing jitter to emulate router being slow to respond at times
Fixes #551

feat(apps): validate routeability through deis-router upon application creation

---

rootfs/registry/dockerclient.py

By setting DOCKER_CLIENT_TIMEOUT as an ENV var it is possible to change the timeout of any of the image operations to do with a Registry
Closes #569
Fixes #489

feat(registry): add the ability to specify a custom timeout for docker client

---

rootfs/scheduler/__init__.py

The way I reproduced it was running a command that does not exist on the pod but instead of getting a failure it would try for 30 seconds and then fail with a "timeout" message

fix(scheduler): deis run could never reach the failed state

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

This provides more security around sensitive information and lets k8s admins put more controls in place on who can update what
Went with a secret per release instead of a secret per app that we keep updating. Thoughts on that?
Closes #299

feat(scheduler): store env vars as secrets in k8s and map them in the RC

---

rootfs/api/models/build.py
rootfs/api/models/release.py
rootfs/api/views.py

In the deploy function Exception is caught, problem logged and then re-raised. Best to catch Exception as well to clean up the release object around it
Potentially affects the following tickets:
#410, #319, #187, #320

fix(deploy): catch Exception instead of RuntimeError

---

rootfs/api/models/config.py
rootfs/scheduler/__init__.py

Added the following new functionalities
* `HEALTHCHECK_PERIOD_SECONDS` - How often (in seconds) to perform the probe
* `HEALTHCHECK_SUCCESS_THRESHOLD` - How many probe runs need to be done after failure to consider it a success again
* `HEALTHCHECK_FAILURE_THRESHOLD` - How many times a probe should fail before considered being down
These defaults are all copied from kubernetes but may have to be adjusted due to our high default timeout, or we bring the default timeout down
Closes #251
Depends on #591 being merged first

feat(health checks): implement new kubernetes 1.2 health check features

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

Before a scale of 1 was hard coded if an old RC could not be found, instead of that use information from the structure in the App model which already defaults to 1 on first deploy
Fixes #607

fix(deploy): use the passed in scale of a proc type for deploy

---

rootfs/requirements.txt

See https://pyopenssl.readthedocs.org/en/stable/changelog.html#id1

chore(requirements): update pyOpenSSL to 16.0.0

---

.travis.yml

This is closer to parity with v9.4.6 currently in use by the [deis/postgres](https://github.com/deis/postgres) component.

chore(.travis.yml): update test PostgreSQL to 9.4

---

rootfs/api/models/release.py
rootfs/registry/__init__.py
rootfs/registry/dockerclient.py
rootfs/registry/tests.py

Unauthenticated registry will show:
```
deis pull quay.io/jhansen/example-go-private:latest -a preset-headwind
Creating build... Error:
400 Bad Request
detail: Permission Denied attempting to pull image quay.io/jhansen/example-go-private:latest
```
non-existent one will show 
```
deis pull foo/bar -a preset-headwind
Creating build... Error:
400 Bad Request
detail: image foo/bar:latest not found
```
In the code I only accounted specifically (so far) for the permission denied scenario and the `not found` is a fairly direct passthrough. For some reason the docker registry API is not setting a `code` of 404 or similar when an image is not found.
I could possibly do some `if 'not found' in error:` kind of dealio to include more information but that's not the cleanest.
Fixes #556
Fixes #616 …

fix(docker): bubble up docker errors from the internal docker client

---

rootfs/deis/settings.py

https://docs.djangoproject.com/en/1.9/ref/databases/#persistent-connections
Maybe the volume to our DB is not enough but majority of our interactions depend on it. It does have a note about dev envs as well

feat(database): persist DB connection for 10 minutes

---

rootfs/api/fixtures/test_sharing.json
rootfs/requirements.txt

See https://github.com/django-guardian/django-guardian/blob/devel/CHANGES
and https://github.com/django-guardian/django-guardian/compare/v1.4.1...v1.4.4
This PR also removes `AnonymousUser` from a test fixture to cooperate with the newer django-guardian library.

chore(requirements): update django-guardian to 1.4.4

---

rootfs/api/tests/test_certificate.py
rootfs/api/tests/test_certificate_use_case_1.py
rootfs/api/tests/test_certificate_use_case_2.py
rootfs/api/tests/test_certificate_use_case_3.py
rootfs/api/tests/test_certificate_use_case_4.py
rootfs/api/tests/test_certificate_use_case_5.py
rootfs/deis/settings.py

Changes all output format from using UTC to using Z, which is ISO8601 compatible
Fixes #625 
See #625 for testing steps - Should see Z instead of UTC on started / updated

fix(models): make dates consistent, output Z instead of UTC for ISO8601 compatibility

---

rootfs/api/management/commands/load_db_state_to_k8s.py
rootfs/api/models/app.py
rootfs/api/models/build.py
rootfs/api/models/release.py
rootfs/api/views.py
rootfs/scheduler/__init__.py

During Controller start all available applications are deployed with their latest release information. Facilitates proper recovery of an application when pulling information from DB only, on a fresh k8s cluster
Fixes #541
Following test steps can be taken:
```
deis create --no-remote rb
Creating Application... done, created rb
remote available at ssh://git@deis.micro-kube.io:2222/rb.git
deis pull deis/example-go -a rb
Creating build... done
micro-kube  (1.2.2) $ k --namespace=rb get po
NAME              READY     STATUS    RESTARTS   AGE
rb-v2-cmd-2iwb2   1/1       Running   0          11s
k delete ns rb
namespace "rb" deleted
k get po
NAME                          READY     STATUS    RESTARTS   AGE
deis-builder-lp5gf            1/1       Running   1          8m
deis-controller-yq1h3 …
```

fix(app): deploy applications on Controller start to create RCs and Pods

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/scheduler/__init__.py

Iterates through all available RCs beside the *latest*, scales them to 0 and deletes. Takes care of the release specific secret as well.
The secret has its own iteration as well in case anything happened on prior runs which made it into an orphan (no RC)
The biggest change here is that the code is not attempting to delete the secret during individual RC deploy but rather as part of the cleanup
after the deploy.
Ref #540
3. do a few releases
4. create an empty RC that uses the same naming scheme as the current one except go a few version in the past
5. run another deis pull
6. verify the hand created RC is gone

ref(release): cleanup old RCs and related kubernetes resources after deploy

---

rootfs/api/models/release.py
rootfs/registry/dockerclient.py
rootfs/registry/tests.py

This will allow for setting username and password for an external registry to pull images from
`IMAGE_AUTH_USER` and `IMAGE_AUTH_PASSWORD` are support via `config:set` and this is per application.
Currently Docker Hub and Quay are supported and a basic support for long lived tokens under gcr.io - ECR is not supported at this time.
For GCR see https://cloud.google.com/container-registry/docs/auth#using_a_json_key_file
The JSON blob needs to be compacted using `jq -c .` or similar before being set
The UX for this will change, very soon. Doing a separate PR for that
Please list the issue(s) that this PR closes, similar to the below:
ref #639
ref #253 
Will come when UX has been sorted out
Will come when UX has been sorted out
https://github.com/deis/workflow/issues/163 …

feat(registry): add initial support to auth to an external Registry on per app basis

---

rootfs/api/management/commands/load_db_state_to_k8s.py

If an application only has releases with no builds (such as a `deis create`),
the restoration process will bail out because an exception was raised,
killing the controller. However, this is not a concern if no build
is associated with the release, so we can just check and ignore
this case.
Closes #650 
None
None
None
1. Create a Cluster with S3 as the backing store
2. Run `deis create`, but don't `deis pull`, `git push`, etc.
3. Destroy the cluster, then create a new one with the same S3 credentials
Results:
1. The controller should be functional.

fix(api): pass if no builds are associated with the release

---

rootfs/api/models/app.py
rootfs/deis/settings.py
rootfs/scheduler/__init__.py

Allows users to set how long k8s allows pods to stay alive after a SIGTERM before they send SIGKILL - Defaults to 30 (like k8s) but lets users set a lower value for faster deploys if the apps can handle it.
Reduces the pod termination wait to the new setting and uses the existance of "deletionTimestamp" as an indicator if a pod is Terminating, also checks if the pod is past the graceful period and hides it from the pod list via ps:list
Fixes #620
Fixes #621
Fixes #631
This change fixes up items marked as pending due to `ps:restart` on a single pod. See #631
This is one slightly hard to test beyond marking the `ps:restart` as not Pending anymore. Most of this code is dealing with Pods that get stuck in Terminating state, see https://github.com/kubernetes/kubernetes/search?q=terminating&type …

feat(scheduler): allow setting gracefulTerminationPeriod and account for in terminations

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py
rootfs/scheduler/states.py

Reasoning here is that we should be showing people more information when we have not specifically covered the bases instead of potentially more obscure information piece, like "initialized"
Also added ContainerCreating as a state to cover a state we had previously not been using for k8s. It got added in 1.2

ref(scheduler): passthrough k8s state if scheduler does not understand it

---

rootfs/api/tests/test_app.py
rootfs/api/views.py

Django Rest Framework will wrap the string with quotes because
of the JSONRenderer. Django's HttpResponse class handles the
application logs as we expect it to.
this is a port of deis/deis#5004
related PRs: deis/workflow-cli#33 and deis/workflow#132

fix(controller): use django HttpResponse for logs

---

rootfs/registry/dockerclient.py

This should have been added previously, but it was missing.

chore(dockerclient): Add workflow-manager to repo blacklist

---

rootfs/registry/dockerclient.py

There was a scenario where the message variable would not get populated and cause a python exception that was not handled

fix(docker client): default to generic message on exceptions

---

rootfs/api/management/commands/load_db_state_to_k8s.py

An application does not have a build attribute, but its latest release does.
closes #668

fix(api): check latest release, not app

---

CHANGELOG.md

[skip ci]
Updates CHANGELOG.md with beta3 changes.

docs(CHANGELOG.md): update for v2.0.0-beta3

---

rootfs/api/models/app.py

Verify application health via router using a higher level python-requests exception instead of just using `ConnectTimeout`. We don't inherently care if things fail with that request as we are giving the `router` some breathing room to apply Nginx configuration
A user (@dwelch2344) ran into a `ConnectionError` issue:
```
INFO Tagging Docker image deis/example-go:latest as 10.0.135.20:80/test:v2
INFO Pushing Docker image 10.0.135.20:80/test:v2
DEBUG create test
DEBUG create test
DEBUG deploy test-v2-cmd, img test:v2, params {'app_type': 'cmd', 'routable': True, 'version': 'v2', 'healthcheck': {}, 'envs': {}, 'replicas': 1, 'tags': {}, 'cpu': {}, 'build_type': 'deispull', 'memory': {}}, cmd ""
DEBUG No prior RC could be found for test-cmd
DEBUG scaling release test-v2-cmd to 1 out of final 1 …
```

fix(app): catch a higher level python-requests exception for verify application health

---

rootfs/api/models/app.py
rootfs/deis/settings.py
rootfs/scheduler/__init__.py

By default the deploy system will take the node count the application is deployed on (using tags), but can also look at `DEPLOY_BATCHES` per application and a global Django django setting with the same name.
Example of the default flow is as follows: As a user I have 5 Nodes my application deploys to, the application has a scale of 17, this will lead to the following deploy cadence:
5, 5, 5, 2 (each item represents a in / out), so 5 pods being brought up 3x and then at the end 2 pods
e2e will use this by default due to the node count it has
A app specific test is also available at https://github.com/deis/workflow-e2e/pull/184
Documentation will come later when we have settled on the env name (may change due to Deployments API, may not)
Please provide a detailed list for how to test the …

feat(deploy): support doing a larger number than 1 in, 1 out deployment

---

rootfs/deis/settings.py

Allow for comma-delimited `RESERVED_NAMES`.
Hard-coded defaults for that env var are also eliminated from the controller itself.  Defaults will be added to the controller's container spec in the chart, thus cluster admins can modify if they choose.
Relates to https://github.com/deis/controller/issues/657

chore(settings): Allow for comma-delimited RESERVED_NAMES

---

rootfs/api/views.py
rootfs/deis/urls.py

Currently the controller pod restarts even if the database is not responding as the check is part of the liveness probe.It is enough if the controller just doesn't respond to requests than restarting as restarting is not gone help anything to make database up and hence it should be as part of the readiness probe. 
2. Register an app to check the controller is responding
3. stop the database
4. now controller should still be running but not serving requests
5. start the database again and controller should start serving requests.

fix(readinessprobe): container shouldn't be restarted if the database is unavailable

---

rootfs/api/models/release.py

ref(release): move RC / Secret cleanup message to emit as DEBUG information

---

rootfs/api/serializers.py
rootfs/api/tests/test_config.py
rootfs/scheduler/mock.py

And the way the regex was written it would also match as many valid chars as it could find, so even one a-z char at the start was saying the name was valid
https://docs-v2.readthedocs.io/en/latest/using-workflow/process-types-and-the-procfile/#declaring-process-types
Following the test case should be enough
3. Create an app that uses a Procfile, use `we&b` as a name for the proc

fix(config): proc type names validation should allow alphanumeric

---

rootfs/requirements.txt

https://github.com/kennethreitz/requests/blob/master/HISTORY.rst#2100-2016-04-29

chore(requirements): Update to python-requets 2.10.0

---

rootfs/api/models/__init__.py
rootfs/api/models/app.py
rootfs/api/models/build.py
rootfs/api/models/certificate.py
rootfs/api/models/config.py
rootfs/api/models/key.py
rootfs/api/models/release.py
rootfs/api/tests/test_auth.py
rootfs/api/views.py

Move to using `DeisException` that extends `APIException` (with 400 as a status code) instead of `EnvironmentError`, have `AlreadyExists` extend `APIException` with 409 and `KubeException` and Logger related exceptions get raised up to the view as `ServiceUnavailable`
Additionally using `from e` when re-raising exception to keep contextual information if that is ever required (https://www.python.org/dev/peps/pep-3134/)
https://github.com/tomchristie/django-rest-framework/blob/master/docs/api-guide/exceptions.md has further info on DRF exceptions
ref #612

ref(models): use DRF APIException as a base for all exceptions

---

rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

After a minute of pulling the image (considered pretty high) then additionl 10 minutes are added on top.
This will help when the cache is cold. Slugrunner and generally big images are being used (1GB or higher generally)
Fixes #459
No e2e for this as it would slow down e2e a lot. From time to time e2e will hit this tho if GKE is being slow
This is a hard one to test due to the need for a big image
3. Run `docker rmi $(docker images -q quay.io/deisci/slugrunner)` against the k8s master
4. Run `make deploy` with this branch
5. `git push` an app
Alternative is to modify the code (locally) and doing a local git commit to Controller itself (for `make deploy`) and changing `seconds = 60` to `seconds = 2` in `scheduler/__init__.py` 
Also, please …

feat(scheduler): add 10 mins to deploy timeout if image pull is slow

---

rootfs/api/tests/__init__.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py
rootfs/requirements.txt
rootfs/scheduler/__init__.py

retry a fixed number of times to find the port exposed by the docker images as docker-py is flaky and raise an exception if the app is routable but no port is specified.
closes #677 
2. Register an app and it should properly
3. Deploy an app with no port exposed in the docker file  and no proc file, you should get an error.

fix(port): retry a fixed number of times to find the port

---

rootfs/api/models/release.py
rootfs/scheduler/__init__.py

Removes the need for Deis registry url being known by the scheduler
Also clarifies what is the `image` and what is the `slug_url` in build pack templates

ref(registry): prepend registry url on images up in Release model

---

rootfs/deis/settings.py
rootfs/scheduler/__init__.py

In all tests the CA issue seems to be gone and it can handle the IP.
Alternatively I tried out https://toolbelt.readthedocs.org/en/latest/adapters.html#fingerprintadapter but that proofed a little annoying since the fingerprints never stayed consistent for whatever reason

fix(scheduler): use CA cert to verify API SSL certficiate

---

rootfs/api/tests/test_api_middleware.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_auth.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_certificate.py
rootfs/api/tests/test_certificate_use_case_1.py
rootfs/api/tests/test_certificate_use_case_2.py
rootfs/api/tests/test_certificate_use_case_3.py
rootfs/api/tests/test_certificate_use_case_4.py
rootfs/api/tests/test_certificate_use_case_5.py
rootfs/api/tests/test_domain.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_key.py
rootfs/api/tests/test_perm.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py
rootfs/api/tests/test_users.py

I triggered an error as an example:
```
======================================================================
FAIL: test_app (api.tests.test_app.AppTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 58, in testPartExecutor
yield
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/case.py", line 600, in run
testMethod()
File "/Users/helgi/projects/deis/controller/venv/src/request-mock/requests_mock/mocker.py", line 180, in inner
return func(*args, **kwargs)
File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py" …
```

chore(tests): output the content/data of the response when status code does not match

---

rootfs/api/tests/test_config.py

`config` tests got omitted somehow in #722

chore(tests): add long message to all assert functions that use status_code checks

---

rootfs/scheduler/__init__.py

This also allowed me to move healthchecks (default and otherwise) under the new _set_container and have deis run make use of it

ref(scheduler): unify how information is applied to the application container object in a Pod template

---

rootfs/scheduler/__init__.py

There is a env secret per version, no point in updating it along the way
If there are many process types then the following ones will *update* the secret and drop the *important* labels

fix(scheduler): do not update env secret if it already exists

---

rootfs/api/models/app.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_scheduler_states.py
rootfs/deis/testing.py
rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py
rootfs/scheduler/states.py

Use the same "is the pod ready" function as normal deployments, also give deis run 20 mins max (arbitrary but is somewhat what the gunicorn worker can do)
On failure the whole Pod manifest is no longer returned. This change affects how we do tests here but minimally
Mocking was improved to help move a Pod from Pending to Running and if it is a deis run Pod (not attached to RC) then it also goes to Succeeded state. This helps with test coverage but is not the full Pod state transition route
Fixes #681
Fixes #590
deis run already has e2e
Documentation still needs to be updated to handle the little change in API
3. run a `deis run` command
4. things should work!

ref(scheduler): rework the way deis run is handled, timeouts and more

---

rootfs/api/tests/test_app.py
rootfs/api/views.py

Depends on https://github.com/deis/controller/pull/738

ref(deis run): change the /run API to use exit_code instead of rc for  the exit code value

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

Not all _pod_state() returns are an Object right now, this is a quick fix for that problem

fix(scheduler): cast PodState to string to get state name

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/api/tests/test_app.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_pods.py
rootfs/api/tests/test_release.py
rootfs/registry/__init__.py
rootfs/registry/dockerclient.py
rootfs/registry/tests.py
rootfs/scheduler/__init__.py

use a k8s Secret to encode a `.docker/config.json` to completely bypass the Controller when it comes to images if a private registry is being used
Handles the various possible errors coming from k8s and bubble that up through to the end user, similar to how the deis dockerclient can do.
k8s adds more information on top of what docker gives so an error message bubbled up from this compared to when the Controller was handling the Docker interaction
ref #639

feat(images): use imagePullSecret when pulling a private image

---

rootfs/scheduler/__init__.py

Instead of using the `Pod` name for `run` templates then instead use the same container name logic as normal application `Pods` have on their app `Container`
Fixes #748
Replaces #749

fix(scheduler): run pod container name did not match how app containers are done

---

rootfs/api/exceptions.py
rootfs/api/models/__init__.py
rootfs/api/models/app.py
rootfs/api/models/certificate.py
rootfs/api/models/key.py
rootfs/api/models/release.py
rootfs/api/tests/test_key.py
rootfs/api/views.py
rootfs/deis/gconf.py
rootfs/deis/settings.py
rootfs/dev_requirements.txt
rootfs/requirements.txt
rootfs/scheduler/__init__.py

Add a custom exception handler to deal with uncaught exceptions so they get properly logged to the stdout logging, and also return a 500 with a JSON body like everything else does.
A lot of scheduling logging has moved up from debug to info (the new default value) and now DEBUG=True (in the django config file) will cause debug information to outputting
`tbgrep` was added, usage would be `k logs -f <controller pod> | tbgrep`
One thing I started doing in this PR is to reduce the `str(e)` as the msg to Exceptions, instead writing more generic message and chaining the Exceptions to together which in turn get logged.
The idea for that is to show end users less internal error messages in API responses but still make it available to the Operator
Please list the issue(s) that this PR closes, …

ref(exceptions/logging): unify logging and make sure exceptions go into logs

---

rootfs/requirements.txt

http://docs.gunicorn.org/en/stable/news.html

chore(requirements): update to Gunicorn 19.6.0

---

rootfs/deis/gconf.py
rootfs/deis/logging.py

If `DEIS_DEBUG` is set then they show up again
Testing Plan:
* `make deploy` on this branch
* `kubectl logs -f <controller pod> --namespace deis`
* See if `/healtz` or `/readiness` show up in the logs (they should not)
* Do any `deis` CLI action and ensure those endpoints show up in the access log
If `DEIS_DEBUG` is set then the those requests should show
Fixes #252

fix(gunicorn): silence healthcheck points in access logs

---

rootfs/deis/gunicorn/config.py

Use `os.cpu_count` instead of `multiprocessing` (they are pretty much the same) - Got added in 3.4: https://docs.python.org/3/library/os.html#os.cpu_count
https://bugs.python.org/issue17914
The default change may seem deceiving but the move from 8 to 4 actually ends up as 9 if CPUs can't be found, due to the math we do
Depends on #758

ref(gunicorn): use os.cpu_count instead of multiprocessing for simplification

---

rootfs/scheduler/__init__.py

An example of this would be a user wanting to overwrite a hardcoded `PORT` or one of the other values Deis may set. Generally people should not do that, however the flexibility should be there in case they want to play with fire
if outputting the information for a given Pod this would be seen - 2x `PORT`
```
env:
- name: PORT
value: "5000"
- name: DEIS_APP
value: finest-rosewood
- name: PORT
valueFrom:
secretKeyRef:
key: port
name: finest-rosewood-v2-env
```
This should only show up once
Fixes #766
3. push a buildpack app
Also, please provide a description of the desired result after the tester completes the above steps.
1. The app called "abcd" should be deployed
2. `kubectl …

fix(scheduler): update instead of appending env vars so hardcoded values can be overwritten

---

rootfs/scheduler/__init__.py

Not all applications will expose a port (non-routable ones)
This builds on top of #769
* Create a Deis Cluster
* Register an app
* push a buildpack app
Also, please provide a description of the desired result after the tester completes the above steps.
* The app called "abcd" should be deployed
* kubectl get pod --namespace=abcd should show 1 pod running
* Get pod information and make sure only one PORT definition is available

fix(scheduler): remove the hardcoded port from RC template

---

rootfs/api/models/app.py

Only set the `PORT` env var if any was found.  By default it seems that k8s / docker will populate `$PORT` based on the service anyway unless we overwrite with our own value
Depends on #769 and #770
Fixes #767 
Fixes https://github.com/deis/workflow/issues/275
It is best to follow the testing steps in the previous tickets and/or what @slack outlined in https://github.com/deis/workflow/issues/275

fix(app): only add a PORT env var if there is a value

---

rootfs/api/models/release.py

This information is useless to the user. Changing the language to bring it in line with the other
port default logs.

fix(api): remove slug tarball info from app log

---

rootfs/dev_requirements.txt

https://github.com/codecov/codecov-python/blob/master/CHANGELOG.md

chore(requirements): update codecov to 2.0.5

---

rootfs/api/models/config.py

The port information comes from the application k8s service instead and has for a long time
Fixes #778
refs https://github.com/deis/workflow/pull/284

fix(scheduler): remove unused health check config option: HEALTCHECK_PORT

---

rootfs/scheduler/__init__.py

when doing config:set PORT=80 then k8s complains that 80 is not a valid port / name
```
deis config:set PORT=80 -a zanier-zirconia
Creating config... Error:
400 Bad Request
detail: zanier-zirconia-v3-cmd (app::deploy): failed to create ReplicationController "zanier-zirconia-v3-cmd" in Namespace "zanier-zirconia": 422 status code 422
{'metadata': {}, 'kind': 'Status', 'reason': 'Invalid', 'status': 'Failure', 'message': 'ReplicationController "zanier-zirconia-v3-cmd" is invalid: spec.template.spec.containers[0].readinessProbe.tcpSocket.port: Invalid value: "80": must be an IANA_SVC_NAME (at most 15 characters, matching regex [a-z0-9]([a-z0-9-]*[a-z0-9])*, it must contain at least one letter [a-z], and hyphens cannot be adjacent to other hyphens): e.g. "http"', 'code': 422, 'apiVersion': …
```

fix(scheduler): cast ports to int before passing them on to k8s

---

rootfs/api/management/commands/load_db_state_to_k8s.py
rootfs/api/models/config.py

This will handle the DeisExceptions and derived Exceptions
Fixes #761
Fixes #741
N/A
N/A 
To test for #741
3. Deploy app with whatever image (`deis/example-go`)
4. Edit a k8s node to have `foo: bar` label
5. `deis tags:set foo=bar -a <app>`
6. Delete RC and Pod from behind Deis for the given app
7. Unset tag on the node
8. Kill the controller pod 
Also, please provide a description of the desired result after the tester completes the above steps.
1. The app called "abcd" should be deployed
2. Find `ERROR: Problem saving to model Config for <app> due to No nodes matched the provided labels: foo=bar` should show up in Controller Logs
3. Controller Pod should be up and running …

fix(management): handle errors in object loading and application deployments instead of throwing exceptions

---

README.md

Refs https://github.com/deis/workflow/issues/285

chore(README): remove references to beta in README

---

rootfs/api/models/app.py
rootfs/requirements.txt

Using `backoff` instead of `retrying` since it offers the ability (built in) to retry on certain exceptions and is also still maintained
Fixes #676

fix(logs): retry fetching logs from the logger 3 times if the services is unavailable

---

rootfs/scheduler/__init__.py

Get the desired number of replicas from the rc instead of counting.
closes #756 
2. Deploy an app
3. Now kill the minio pod so that the image is not present
4. scale the rc so that they are in crash loop back status(this is bug which will be fixed in another PR) and now if you scale it does nothing.
5. after the fixes when you scale down it should do it.

fix(scale):get the desired number of replicas from the rc

---

rootfs/Dockerfile

Copying of code is done as a separate step so that the cache on that can be busted
This speeds up development *a lot*
Fixes #303
```
make deploy
docker build --rm -t quay.io/helgi/controller:git-89f49a6 rootfs
Sending build context to Docker daemon 324.1 kB
Step 1 : FROM quay.io/deis/base:0.3.0
---> 4d150961c772
Step 2 : RUN adduser --system 	--shell /bin/bash 	--disabled-password 	--home /app 	--group 	deis
---> Using cache
---> ee8f8856b909
Step 3 : COPY requirements.txt /app/requirements.txt
---> Using cache
---> 1cd091f64c74
Step 4 : RUN buildDeps='gcc git libffi-dev libpq-dev python3-dev'; 	apt-get update && 	apt-get install -y --no-install-recommends         $buildDeps         libpq5         python3         libpython3.5-dev         sudo &&   ln -s /usr/bin/python3 /usr/bin/python && …
```

ref(Dockerfile): only trigger package installation if requirement.txt changes

---

rootfs/scheduler/__init__.py

https://github.com/deis/controller/pull/790 changed the nature of how scaling works (for the better) but it had the side effect of relying on `spec/replicas` to not be set to the desired value off the bat.
In the past deploys always started at 0 and incremented up but ultimately that caused issues due to hardcoding and so it was changed so RCs would be created with the *initial* value set properly.
That didn't really gel well with #790 as it was doing a `desired == current` (desired being 1 and current being `spec/replicas`) which means `_scale_rc` was never waiting for the initial `cmd/web` Pod to come up
3. `deis pull deis/example-go`
4. Make sure the pull waits until the …

fix(scheduler): make deploy have 0 replicas by default and then use scaling to go up

---

rootfs/scheduler/__init__.py

In some cases when a release is cleaned up an orphaned secret env is left behind. This will overwrite any orphaned ones.
I will look into the cleanup logic to also delete the env secret in a follow up PR but this makes other PRs I have going on work and is far quicker.

fix(secrets): update env secrets if they already exists (overwrites existing values)

---

rootfs/api/models/config.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_config.py

Prior to this the PORT was defaulting to 5000 instead.
Fixes #775
https://github.com/deis/workflow-e2e/pull/223
refs https://github.com/deis/workflow/pull/289
3. use `registry:set` and observe a failure
4. set `PORT`
5. Make sure `registry:set` works now

feat(release): require PORT to be set when private registry is set

---

rootfs/api/serializers.py
rootfs/api/tests/test_config.py

Other config items use this and there was a probelm where config:unset was getting caught on trying to validate that PORT was numeric

fix(serializer): skip None values in config and registry

---

rootfs/requirements.txt
rootfs/scheduler/__init__.py

Reasoning behind this is everyone looks at k8s information via YAML. It is much easier to read
Uses https://yaml.readthedocs.io/en/latest/index.html instead of PyYAML as it is basing off it anyway
Decided not to change the `string.Template` approach, yet.

ref(scheduler): move scheduler templates from JSON to YAML

---

rootfs/api/models/app.py
rootfs/api/tests/__init__.py
rootfs/api/tests/test_app.py
rootfs/scheduler/__init__.py

Just some housekeeping. It's logic more pertaining to the App model than the scheduler

ref(scheduler): move a few high level scheduling functions to the App model

---

rootfs/api/exceptions.py
rootfs/api/models/config.py
rootfs/api/tests/test_release.py

http://www.bennadel.com/blog/2434-http-status-codes-for-invalid-data-400-vs-422.htm is a good explanation of the differences between 400 and 422 and why I picked 422
Requires https://github.com/deis/workflow-e2e/pull/236

fix(config): return a 422 if unsetting a config key that does not exist

---

rootfs/api/models/release.py
rootfs/api/tests/test_release.py

This replaces logging that nothing changed for the release and still going ahead with the release. Now it is a noop operation.
Fixes #321
3. `deis pull deis/example-go -a <app>
4. `deis config:set foo=bar -a <app>`
5. `deis config:set foo=bar -a <app>`
Also, please provide a description of the desired result after the tester completes the above steps.
A `409` response should be seen

feat(release): throw 409 when identical release is done sequantially

---

rootfs/deis/gunicorn/config.py

Doubles the default value for gunicorn workers, which increases responsiveness to a point where e2e tests seem to pass reliably with `GINKGO_NODES=30`, at the cost of more memory.
See http://docs.gunicorn.org/en/stable/design.html#how-many-workers and http://docs.gunicorn.org/en/stable/settings.html#workers.
Refs deis/workflow-e2e#215.
Replaces #835.

ref(gunicorn/config.py): double default worker count

---

rootfs/api/settings/production.py

Logs all SQL queries to stdout if DEBUG==True:
```
+ python /app/manage.py load_db_state_to_k8s
+ sudo -E -u deis gunicorn -c /app/deis/gunicorn/config.py api.wsgi
[2016-06-22 22:36:32 +0000] [23] [INFO] Starting gunicorn 19.6.0
[2016-06-22 22:36:32 +0000] [23] [INFO] Listening at: http://0.0.0.0:8000 (23)
[2016-06-22 22:36:32 +0000] [23] [INFO] Using worker: sync
[2016-06-22 22:36:32 +0000] [26] [INFO] Booting worker with pid: 26
[2016-06-22 22:36:32 +0000] [28] [INFO] Booting worker with pid: 28
[2016-06-22 22:36:32 +0000] [30] [INFO] Booting worker with pid: 30
[2016-06-22 22:36:32 +0000] [32] [INFO] Booting worker with pid: 32
[2016-06-22 22:36:32 +0000] [33] [INFO] Booting worker with pid: 33
DEBUG (0.001) SELECT "api_key"."uuid", "api_key"."created", "api_key"."updated", …
```

feat(settings): log all SQL queries if DEBUG==True

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

Previously only the failing RC would get fixed up but now the whole state will be reverted if one RC fails
I marked it as a `fix` as I felt the potential inconsistency in the app state was broken

fix(scheduler): if one RC fails to scale then ensure all other RCs are at the right level

---

rootfs/api/models/release.py
rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

Makes it possible to use a `notin()` and `in()` filter.
This can be achieved by using this syntax: `version__notin(v3, v4, v5)` or `type__in(cmd, web, public)`
set based filtering makes it easy to exclude the latest version of a resource (based on a deis version). It is possible to combine filters as well

feat(scheduler): add support for set based requirement filtering via the kubernetes API

---

.github/PULL_REQUEST_TEMPLATE

We've found that half of the engineering team either hates or doesn't even bother using the PR
templates. Refactoring it down to the bare minimum should suffice.

docs(github): simplify pull request template

---

rootfs/api/serializers.py
rootfs/api/tests/test_domain.py
rootfs/api/views.py
rootfs/requirements.txt

Hi, I have rewritten the validation code of `DomainSerializer ` to support IDN domains.
If a Unicode domain is added to an app, it is stored in ASCII compatible encoding (ACE).
Adjusted `DomainViewSet` so it maps Unicode input to ACE.
Created test `test_manage_idn_domain`, modified tested domains for `test_manage_domain` and `test_manage_domain_invalid_domain` to reflect the changes regaring IDN support.
Adds [python package idna](https://pypi.python.org/pypi/idna) as new dependency to the project.
closes #318
See also https://github.com/deis/router/commit/76ea246732f6987951913877a7d0a24ed0619c9c, I am going add a PR for this commit too.

feat(IDN): add support for international domains

---

rootfs/api/models/release.py
rootfs/api/tests/test_release.py

Kubernetes requires the port number to be an integer or else it assumes that it is a named port.
fixes #856

fix(scheduler): cast port to an int from environment

---

rootfs/bin/boot

on some providers, the docker socket is owned by the root group. We want it to be owned by docker
so the controller can connect to the socket.
closes #801 
N/A since this occurs only on vagrant
N/A
N/A
1. Create a Deis Cluster on Vagrant using kube-up.sh
3. Deploy an app using `deis pull`
Results:
1. The app called "abcd" should be deployed.

fix(boot): change group ownership of docker socket

---

rootfs/api/models/release.py
rootfs/api/tests/test_release.py

v1 is an intial release created when `deis create` is called, but
does not contain any build information.
addresses https://github.com/deis/workflow/issues/275#issuecomment-222801645
N/A
N/A

fix(api): fail when rolling back to v1

---

rootfs/scheduler/__init__.py

Makes it easier to debug when order stays consistent, especially with something like `deepdiff`

feat(scheduler): sort env vars and secrets by keys for easier hashing

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/api/tests/test_release.py

Env Vars are stored in a Secret, where there is 1 secret per Release. This causes a situation where non-web/cmd proc types will overwrite the Secret data during deploys.
This is the only way possible (for now) since env vars are per Release and not per proc type

fix(release): return port from get_port for non-routable process types

---

rootfs/api/exceptions.py
rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/api/settings/production.py
rootfs/api/tests/deployments/test_app.py
rootfs/api/tests/deployments/test_build.py
rootfs/api/tests/deployments/test_certificate.py
rootfs/api/tests/deployments/test_certificate_use_case_1.py
rootfs/api/tests/deployments/test_certificate_use_case_2.py
rootfs/api/tests/deployments/test_certificate_use_case_3.py
rootfs/api/tests/deployments/test_certificate_use_case_4.py
rootfs/api/tests/deployments/test_certificate_use_case_5.py
rootfs/api/tests/deployments/test_config.py
rootfs/api/tests/deployments/test_domain.py
rootfs/api/tests/deployments/test_hooks.py
rootfs/api/tests/deployments/test_pods.py
rootfs/api/tests/deployments/test_release.py
rootfs/api/tests/test_build.py
rootfs/api/tests/test_hooks.py
rootfs/api/tests/test_pods.py
rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

TODO:
Closes #19 
Requires deis/workflow-e2e#251
Requires deis/workflow#369
This adds Deployment object support (replaces ReplicationController) when a feature flag is enabled. This can be done by either settings a global ENV Var on the Controller or setting a config per app. The variable is `DEIS_KUBERNETES_DEPLOYMENTS=1`
A few new features (Deployments only) have been introduced or specifically expose Deployment functionalities:
* `KUBERNETES_DEPLOYMENTS_REVISION_HISTORY_LIMIT` (global and per app setting) specifies how many revisions (ReplicaSets) to keep
* Stop concurrent deployments (triggered by push, pull, config:set and so on)
If Deployments is enabled on an existing app then a whole new copy will be spun up (behind the scenes) as Deployment and then the old ReplicationController …

feat(*): add Deployments support behind a feature flag

---

Makefile
rootfs/scheduler/__init__.py
rootfs/scheduler/tests/test_scheduler.py

fix(scheduler): only attach healthcheck if app is routable

---

rootfs/api/models/config.py
rootfs/api/tests/deployments/test_config.py
rootfs/api/tests/test_config.py
rootfs/scheduler/__init__.py

Also get the max() between liveness and readiness initial seconds delay to use in deploy timeout. It is smart enough to deal with if one or both are missing as well.
Fixes #874

fix(healthchecks): when migrating from old healthchecks also add in readiness probe

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/api/settings/production.py
rootfs/scheduler/__init__.py

This will behave slightly differently between the old deploy method (RC) and Deployments
RC workflow: `DEIS_DEPLOY_TIMEOUT` refers to the base timeout *per* each `DEIS_DEPLOY_BATCHES`
Deployment workflow: `DEIS_DEPLOY_TIMEOUT` is the base timeout which then gets multipled with `DEIS_DEPLOY_BATCHES` to get an overall timeout
closes #817
[docs](https://github.com/deis/workflow/pull/374)

feat(app): make deploy timeout configurable globally/per-app via DEIS_DEPLOY_TIMEOUT, default is 2 minutes

---

rootfs/api/models/app.py
rootfs/api/tests/deployments/test_pods.py
rootfs/api/tests/test_pods.py
rootfs/scheduler/__init__.py

This code used to be necessary to prevent systemd abuse. Now that kubernetes handles the escaping
for us, there is no need to be super defensive in our own code.
closes #821 
closes https://github.com/deis/deis/issues/5060

fix(api): remove command escaping from v1

---

rootfs/api/models/app.py

Instead of 10.026906251907349 it would show 10 or 11 as there is no need to show that precision level

fix(app): round the log message wait time using bankers rounding

---

rootfs/requirements.txt

See docs.djangoproject.com/en/1.9/releases/1.9.8/
These changes don't appear to affect Deis Workflow at first glance, so I don't think this is a high priority to merge. It can go in v2.3.0 IMHO.

chore(requirements): update Django to 1.9.8

---

rootfs/scheduler/__init__.py
rootfs/scheduler/tests/test_scheduler.py

fix(scheduler): lower case CPU limits and upper case first char in Memory limits for Kubernetes

---

rootfs/scheduler/__init__.py
rootfs/scheduler/tests/test_scheduler.py

docker-py will return hostname as 'docker.io' if the image is from dockerhub  but the server address is different than that.
fixes #919

fix(registry): Use proper hostname for dockerhub images

---

rootfs/api/serializers.py
rootfs/api/tests/test_config.py
rootfs/requirements.txt

Kubernetes has this restriction, catch it before it ever makes it that far.
Introducing jmespath now to later use in other places as well
Fixes #873

fix(validation): success threshold can only be equal to one when setting liveness probe. Error properly

---

rootfs/api/models/app.py
rootfs/api/tests/deployments/test_pods.py
rootfs/api/tests/test_pods.py

fix(scale): return a 404 instead of 400 when scale uses a proc type that does not exist

---

rootfs/api/middleware.py
rootfs/api/tests/test_api_middleware.py

This removes code that is used to do a server side version check of the client. This hasn't been used in a very long time, as now the logic for api version mismatches is entirely client side.

fix(middleware): remove unused server side version check

---

rootfs/requirements.txt

django-cors-headers is inactive and django-cors-middleware is a fork of the former

chore(requirements): move from django-cors-headers to django-cors-middleware

---

rootfs/api/models/app.py
rootfs/api/settings/production.py
rootfs/scheduler/__init__.py

Prior to this the application config was being created inside `_set_container` which gets called for every proc type, yet we share this single config across all proc types (currently)

fix(scheduler): create application config (env secrets) outside of deploy / scale to reduce k8s thrasing

---

rootfs/api/tests/test_app.py
rootfs/api/views.py

Check if command exists before trying to access it.

fix(run): return a 400 if command is empty

---

rootfs/api/tests/test_auth.py
rootfs/api/views.py

Previously, passwd didn't check if `password` or `new_password` was set resulting in server errors when trying to access them.
I haven't wrote any tests, cause I wanted to make sure this was the right approach.
I was also looking at serializers, but it doesn't seem like you can override the serializers on a per-view basis. I'm also concerned about using a `DeisException`, because I would rather have a field specific error, like serializers do.
1. Create a normal user.
2. Try `POST /v2/auth/passwd` without `new_password` or `password` and make sure 500 errors are returned.

fix(passwd): raise 400 when password is not a parameter

---

rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py
rootfs/scheduler/tests/__init__.py
rootfs/scheduler/tests/test_deployments.py
rootfs/scheduler/tests/test_namespaces.py
rootfs/scheduler/tests/test_nodes.py
rootfs/scheduler/tests/test_pod_states.py
rootfs/scheduler/tests/test_replicationcontrollers.py
rootfs/scheduler/tests/test_scheduler.py
rootfs/scheduler/tests/test_secrets.py
rootfs/scheduler/tests/test_services.py
rootfs/scheduler/tests/test_utils.py
rootfs/scheduler/utils.py

This expands the scheduler test suite and can run outside of the API setup. Brings is simple testing per resource type.
Also fixes a few mock and scheduler discrepencies that were discovered in the testing

feat(scheduler): add scheduler tests that do not go through normal api tests

---

rootfs/scheduler/__init__.py

If an app is not routable, then the scheduler should remove the "routable" annotation from the application's service.
This is blocked by a bug in the router: https://github.com/deis/router/issues/233
closes #973

fix(scheduler): make app un-routable

---

rootfs/scheduler/__init__.py
rootfs/scheduler/mock.py

This detect errors from the pods event stream by turning the image error handling code into something slightly more generic so we can expand it over time if need be
```
Events:
FirstSeenLastSeenCountFromSubobjectPathTypeReasonMessage
------------------------------------------------------------
4m1m2{default-scheduler }WarningFailedSchedulingpod (gaslit-joyrider-cmd-2657344266-tv41n) failed to fit in any node
fit failure on node (ip-172-20-0-109.us-west-2.compute.internal): Node didn't have enough resource: CPU, requested: 2000000, used: 520, capacity: 2000
```
I made the "failed deploy, going back to old release" contain more contextual information. This can be good but may also get to be busy... Could change it so we log the additional information but do not return it via the API
1. …

fix(scheduler): when user asks for limits beyond their allowance then error out faster

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/scheduler/__init__.py

It is possible to get a Deployment into a state where it can not bring up pods. The API will think that means that the Deployment is still "in progress". The scenario around this mostly happens when the client connection (CLI) is lost and the API loses context.
This change brings in the ability to get past the "in progress" stop sign when the Deployment is found to have errors (image not found, limits are bad, etc) or it has been in that state for more than the overall deploy timout limit is
Fixes #706
Refs #785
Replaces #792
* Create a Deis Cluster
* `deis create --no-remote progress
* `deis pull deis/example-go -a progress`
* `deis limits:set -c cmd=9999999 -a progress` (this should fail)
* `deis config:set foo=bar -a progress` (this should succeed)
* `deis limits -a progress` (this …

fix(scheduler): allow Deployment "in progress" to be bypassed in case of errors or timeout

---

rootfs/scheduler/__init__.py
rootfs/scheduler/tests/test_replicationcontrollers.py

These can always be brought back if the same logic is required for RS (due to diff deploy strategy than Deployments offers)

ref(scheduler): remove scale_rc and deploy_rc as they are no longer used

---

rootfs/registry/dockerclient.py

fix(registry): retry pull/push/tag 3 times - should help with slow networks and slow registries

---

rootfs/api/models/release.py
rootfs/api/tests/test_release.py
rootfs/scheduler/tests/test_scheduler.py

registry:set does the same kind of warning but since this is a whole platform setting then we need to warn on deploy as well
Fixes #986
Requires off-cluster native iaas cluster to test
```
deis create --no-remote
Creating Application... done, created august-sandwich
If you want to add a git remote for this app later, use `deis git:remote -a august-sandwich`
deis pull deis/example-go -a august-sandwich
Creating build... Error: Unknown Error (400): {"detail":"PORT needs to be set in the config when using a private registry"}
deis config:set PORT=80 -a august-sandwich
Creating config... done
=== august-sandwich Config
PORT      80
deis pull deis/example-go -a august-sandwich
```

fix(registry): tell a user they need PORT when using off-cluster native iaas registry

---

rootfs/Dockerfile

Has pre-created man page directories to work around an issue with `apt-get install postgresql-client,` for one example.
Refs deis/docker-base#6. Ping @jgmize.

chore(rootfs/Dockerfile): update to latest base image

---

rootfs/api/middleware.py
rootfs/api/models/certificate.py
rootfs/api/serializers.py
rootfs/api/settings/production.py
rootfs/api/views.py
rootfs/requirements.txt

Waiting for https://github.com/zestedesavoir/django-cors-middleware/pull/25 to land as we are blocked on that for now

fix(middleware): move to 1.10 style middleware

---

rootfs/scheduler/mock.py

Makes for a cleaner session mock and interacts more with how the main scheduler works

ref(scheduler): use scheduler module session singleton to add session mock

---

rootfs/api/models/__init__.py

This change caused e2e to fail because it expects the class name to be lower case.

fix(models): add "_added" log function, lowercase class name

---

rootfs/requirements.txt

https://github.com/pyca/pyopenssl/blob/master/CHANGELOG.rst#1610-2016-08-26

chore(requirements): update PyOpenSSL to 16.1.0

---

rootfs/api/models/app.py
rootfs/scheduler/resources/pod.py
rootfs/scheduler/tests/test_deployments.py
rootfs/scheduler/tests/test_horizontalpodautoscaler.py
rootfs/scheduler/tests/test_replicationcontrollers.py

This makes a few internal methods now fetch the timeout from the pod instead of depending on outside info, previously it was fetching the info from global django.settings object.
Makes `pod_termination_grace_period_seconds` a required param for a few scheduler methods, like we already have with `app_type` etc etc
Close #807

feat(scheduler): add the ability to set KUBERNETES_POD_TERMINATION_GRACE_PERIOD_SECONDS per application

---

rootfs/scheduler/mock.py
rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/replicationcontroller.py
rootfs/scheduler/resources/scale.py

Prior to this a full resource update was being done during a scale event, this could lead to potential pod template updates that were not desired
Fixes #1012

feat(scheduler): use /scale endpoints for RC and Deployments to only update replicas during scale events

---

rootfs/api/models/app.py
rootfs/api/tests/test_app.py
rootfs/scheduler/resources/pod.py
rootfs/scheduler/tests/test_scheduler.py

The issue is that multiple process types can cause 409 issues when ran in the async process. It's fine to run this ahead of any deploy as this secret is not tied to the release version of an application
Moved pull image secret and registry config generation into the App model as it makes more sense given where it gets used.
Also reduces `django.settings` in the `scheduler`
Fixes #1031

fix(app): create image pull secrets outside of the async deploy loop

---

rootfs/api/__init__.py
rootfs/api/models/app.py
rootfs/api/tests/test_app.py

When python-requests got data from logger it was in binary string format, converting that to normal string was sufficient
Docs change https://github.com/deis/workflow/pull/485
Fixes #1033

fix(logs): app logs endpoint was returning binary string instead of a normal string

---

rootfs/api/models/app.py
rootfs/scheduler/resources/deployment.py

Prior to this the wrong variable was being passed and as such the revision history feature did not work

fix(scheduler): pass down the right variable for Deployment revision history limit

---

rootfs/api/models/app.py
rootfs/scheduler/__init__.py

Previously only the failed process type would roll itself back, resulting in a scenario where worker may be on v6 and web on v5
This moves away from using the built in rollback functionality in Deployments and rather deploys the previous release again to get the same effect.
Rollback in Deployments was taking it to the last good known deployment, in this case that'd be the latest for some types... knowing the revision of the last deploy would be hard as well.
The way it works when deploying the old release is an identical replicaset (and thus identical template pod hash is generated) so things will very much so look like a native rollback.
If the Controller has done any changes to how it constructs the pod manifest then this could generate a totally new ReplicaSet but that is also fine as …

fix(app): rollback all process types to previous version when one (or  more) process type fails a deploy

---

rootfs/api/models/release.py
rootfs/scheduler/__init__.py

Before the cleanup process and Release::delete were removing RCs and env secrets related to all but current releases, this can (and has) gotten all screwy in the logic due to how RC and Deployment cleanup ended up being merged instead of being previously separate.
Now the process it so cleanup non-latest RCs (just as a safety thing), and only remove secrets that are not associated to a specific ReplicaSet

fix(release): change release cleanup to only remove secrets related to Deployments that are no longer active

---

rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/pod.py

fixes #989 
Testing Instructions:
1) deploy an app(example-go) and make sure its working
2) now set an readiness healthcheck such that it fails `deis healthchecks:set readiness httpGet 2000 --type web` so that the new deploy is failed
3)without this pr changes the command should execute fine after this PR changes the deploy should rollback to previous release.

fix(healthcheck): check if the healthchecks are failing on a new deploy

---

rootfs/api/models/app.py
rootfs/api/tests/test_tls.py

This PR creates a TLS object when an application is created, fixing the issue where a server error is shown after `deis tls:info` is called after `deis create`.
closes #1042

fix(api): create TLS object on app create

---

rootfs/api/tests/test_certificate_use_case_1.py
rootfs/api/views.py

Made it so a user can pass /v2/apps/foo/domains/thing.com or pass {domain: thing.com} as the body
This works because DELETE uses the former format and POST (including SDK) use the latter but the URL format supports POST doing both... Should probably drop the body element at some point when we can break the API

fix(views): make sure domain is set it in cert attach operation

---

rootfs/Dockerfile

ref(Dockerfile): ditch the pip cache for a slightly smaller image

---

rootfs/scheduler/__init__.py
rootfs/scheduler/resources/__resource.py
rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/horizontalpodautoscaler.py
rootfs/scheduler/resources/namespace.py
rootfs/scheduler/resources/node.py
rootfs/scheduler/resources/pod.py
rootfs/scheduler/resources/replicaset.py
rootfs/scheduler/resources/replicationcontroller.py
rootfs/scheduler/resources/scale.py
rootfs/scheduler/resources/secret.py
rootfs/scheduler/resources/service.py
rootfs/scheduler/tests/test_kubehttpclient.py

These functions properly handle connection errors and clean up some of the child/parent class
relations when making a request.
closes #1008

ref(scheduler): add HTTP functions in KubeHTTPClient

---

rootfs/requirements.txt

https://github.com/django-guardian/django-guardian/releases/tag/v1.4.6

chore(requirements): update django-guardian to 1.4.6

---

rootfs/scheduler/exceptions.py

With the response below the user would get the very unhelpful `422 Invalid` - This extends that
```
{
'code': 422,
'reason': 'Invalid',
'apiVersion': 'v1',
'metadata': {},
'kind': 'Status',
'details': {
'kind': 'Service',
'causes': [
{'field': 'spec.clusterIP', 'reason': 'FieldValueInvalid', 'message': "invalid value '', Details: range is full"}
],
'name': 'test-760092409'
},
'message': 'Service "test-760092409" is invalid: spec.clusterIP: invalid value \'\', Details: range is full',
'status': 'Failure'
}
```

fix(scheduler): show more information when there is a HTTP error in Kubernetes

---

rootfs/requirements.txt

https://github.com/docker/docker-py/blob/master/docs/change_log.md#1100
@kmala do you want to add anything into this PR that uses https://github.com/docker/docker-py/pull/1133/files ?

chore(requirements) Update to docker-py 1.10.2

---

rootfs/api/models/app.py
rootfs/api/settings/production.py
rootfs/scheduler/resources/pod.py

Removes the last of django.settings from scheduler main line code (not tests)
IMAGE_PULL_POLICY is now the only thing used and can be set per app, SLUG_RUNNER_IMAGE_PULL_POLICY has been removed

ref(scheduler): move image pull policy settings from scheduler to App model and remove SLUG_RUNNER_IMAGE_PULL_POLICY

---

rootfs/api/models/app.py

This removes the unnecessary warnings from router logs
```
WARNING: Field "router.deis.io/whitelist" value "" does not satisfy constraint /^((([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))?(\s*,\s*)?)+$/ -- skipping this field and using default value "[]".
```

fix(whitelist): remove the whitelist from annoations if its empty

---

rootfs/api/tests/test_app.py

used has_calls instead of assert_called_with since there are other logs knocking around from AppSettings and others that are not relevant in this test
Closes #597

chore(tests): port app logs test from deis/deis#5005

---

rootfs/api/models/app.py
rootfs/api/tests/test_app.py

fix(api): check if release.build is NoneType

---

rootfs/api/models/app.py
rootfs/api/settings/production.py
rootfs/api/tests/test_app.py

Otherwise it will be a string in the scheduler code and break it.
closes deis/builder#429

fix(api): cast DEPLOY_BATCHES and DEPLOY_TIMEOUT to int

---

rootfs/api/models/app.py
rootfs/api/tests/test_app.py

closes #1057 
rebased off of #1078 for the _build_env_vars tests, see e88c52f for the new commit.

feat(api): inject release metadata into application

---

rootfs/scheduler/tests/test_horizontalpodautoscaler_12_lower.py

ref #60
Created a 1.2 (and lower) test and 1.3 and higher test

chore(tests): improve test coverage for HPA

---

rootfs/Dockerfile

Use `python3-pip` instead of using non-package management approach as this provides us with the proper pip version anyway, and better cleanup
Old vs New image size:
```
REPOSITORY                TAG                 IMAGE ID             SIZE
quay.io/deis/controller   v2.5.1              8e926c780d4d         214.4 MB
quay.io/helgi/controller   canary              a1017a79f8a2       204.8 MB
```

ref(Dockerfile): use base 0.3.4, smaller packages and better cleanup

---

rootfs/api/models/release.py

I pulled my hair out for quite a bit of time because of the error I got, mentioned in deis/builder#433 
😄 
For me personally it would have helped if the error:
```
Error running git receive hook [publishing release (Unknown Error (400): {"detail":"PORT needs to be set in the config when using a private registry"})]
```
mentioned that it was about the application config, and not the registry config. Hence this pull request. Hope it helps others!
I'm not sure about convention, or I would have even put the URL to the corresponding docs in there, with a:
> See: https://deis.com/docs/workflow/installing-workflow/configuring-registry/#configuring-off-cluster-private-registry
Please let me know your thoughts and I can take care of that as well.
Cheers!

Clarify PORT error when using private registry

---

rootfs/registry/dockerclient.py
rootfs/requirements.txt

Concurrent pull issue was resolved in 1.9 (https://github.com/docker/docker/issues/9718) and Kubernetes is validated against that as well
I can update https://deis.com/docs/workflow/installing-workflow/system-requirements/ with the required info if we want to go with this change

ref(registry): remove simpleflock and depend on Docker 1.9 minimum

---

rootfs/api/exceptions.py
rootfs/api/tests/test_config.py

Right now if you run a `deis config:list` outside of a deis repo you will still see a `Not Found` instead of a good message but that is due to how SDK / CLI handles errors.
I forced it to a random status code and get this back
```
deis config:list
Error: Unknown Error (418): {"detail":"Config was not found."}
```
Note that the app is missing but `Config` is the info since it happens within the config view, which is the only thing I get to plug into - Additionally there is no info about _what_ is missing if we were actually showing that App is missing. DAMN YOU DRF...
closes #893

feat(errors): give more context on what model is involved when 404 Not Found is involved

---

rootfs/api/models/app.py
rootfs/scheduler/resources/pod.py

Create the objectstore secret before deploying as the current approach can cause 409 issues when multiple proctypes are present.
The error scenario can happen when moving from one k8s cluster to another cluster with external storage because of a cluster crash or any other reasons or during an upgrade from pre-deployments support in workflow(2.1/2/3) to latest.

fix(secret):create objectstore secret before calling scheduler deploy

---

rootfs/api/exceptions.py
rootfs/api/models/build.py
rootfs/api/settings/production.py
rootfs/api/tests/test_build.py

Add 2 new settings, only available globally
`DEIS_DEPLOY_REJECT_IF_PROCFILE_MISSING` rejects a deploy if the previous build had a `Procfile` but the current deploy is missing it for some reason. A `409` is thrown
`DEIS_DEPLOY_PROCFILE_MISSING_REMOVE` when set to `false` will allow an empty `Procfile` to go through without remove missing process types if the previous build had a `Procfile`
ref #1062

fix(deploy): add global settings DEIS_DEPLOY_PROCFILE_MISSING_REMOVE and DEIS_DEPLOY_REJECT_IF_PROCFILE_MISSING

---

rootfs/requirements.txt

https://pyopenssl.readthedocs.io/en/stable/changelog.html#id1

chore(requirements): update PyOpenSSL to 16.2.0

---

Makefile
README.md

Remove instructions for installing PostgreSQL via Homebrew; also check that Docker is installed before executing `make postgres`.

docs(README) Refer to postgres setup in Makefile

---

rootfs/api/permissions.py
rootfs/api/tests/test_perm.py

This can be a first step in providing different options on what the default registration mode can be.
Now the user can install workflow with `admin_only`  as default and register himself as the admin user without having to change the manifest after install.

fix(registration): allow admin user registration when the mode is admin_only

---

README.md

Installing Python 3.5 via Homebrew doesn't make it usable right away; python/pip 2.x via Homebrew will be used by default. More importantly, Homebrew isn't great at managing multiple versions of Python/Ruby/etc., but `pyenv` makes it easy to install and switch between Python versions.
I hit this issue attempting to setup my dev environment for this project; I think this will reduce the barrier to entry a bit.

docs(README): Recommend installing python 3.5 via pyenv on macOS

---

rootfs/api/serializers.py
rootfs/requirements.txt

http://www.django-rest-framework.org/topics/3.5-announcement
The lack of a fields class variable was causing problems. The lack of it was deprecated in 3.3 and finally removed in 3.5
Deprecates #1117

chore(requirements): update to DRF 3.5.1

---

rootfs/bin/boot

Currently debug output is turned on if `DEIS_DEBUG` is set to anything (including `DEIS_DEBUG=FALSE`). This requires it be explicitly `true`, like the rest of the code base.

Ensure DEIS_DEBUG==true for debug output

---

rootfs/api/serializers.py
rootfs/api/tests/test_build.py

fixes https://github.com/deis/controller/issues/1124
Not adding the regex to support underscore because kubernetes doesn't support it in the names and it is better to not add it than make changes internally from `_` to `-` which is might be prone to errors.
But if it is really important to have support for the `_` then i am open to adding it.

fix(proctype): Change the regex used for validating proctypes

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/api/tests/test_release.py

fixes #1015 
If the app is non-routable then don't throw error if port can't be found.

fix(port): Port can be made optional for non-routable apps

---

rootfs/scheduler/mock.py
rootfs/scheduler/tests/test_deployments.py

This error occurs when the registry hosting the image being pulled by `deis pull` (or, in the case
of `git push deis master`, quay.io/deis/slugrunner) becomes unreachable. This test confirms that
master has fixed the original error, which is that a KubeException used to be raised, being
uncaught in older releases of Workflow. This has since been fixed in master by raising KubeHTTPException, which will raise the 503 and roll back the release rollout.

tests(scheduler): confirm "network unreachable" raises KubeHTTPException

---

rootfs/requirements.txt

See https://github.com/litl/backoff/releases/tag/v1.3.2

chore(requirements): update backoff library

---

rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/pod.py

`seconds` variable didn't exist

fix(timeout-debug-msg): unresolved variable

---

rootfs/requirements.txt
rootfs/scheduler/__init__.py
rootfs/scheduler/resources/horizontalpodautoscaler.py
rootfs/scheduler/tests/test_horizontalpodautoscaler_12_lower.py

Since the server version can be any valid string type, it is incorrect to assume that the minor
version can be converted into a float value. Instead, it is better to compare it as a string using
the semver package.
closes #1159.

fix(scheduler): use semver package to compare server version

---

Makefile

pyvenv has been officially deprecated in favour of `python3 -m venv` as of the python 3.6 announcement made this morning.
This command also works in previous python versions. I have manually tested this with python 3.5.2 without issues. The `@if [ ! -d venv ];` check is no longer necessary as the venv module identifies if it already exists and just exits zero.

chore(Makefile): remove pyvenv script

---

rootfs/api/models/domain.py

fixes #1172 
certificate.detach() calls domain.save() which updates the service annotation with the domain again.Hence remove the domain annotation after detaching the certificate.

fix(domain): remove the annotation when domain is deleted

---

rootfs/api/models/app.py
rootfs/api/settings/production.py
rootfs/api/settings/testing.py
rootfs/scheduler/mock.py
rootfs/scheduler/resources/quota.py
rootfs/scheduler/tests/test_quota.py

If set KUBERNETES_NAMESPACE_DEFAULT_QUOTA_SPEC to something like:
`{"spec":{"hard":{"cpu":"3","pods":"10","secrets":"10"}}}`
```json
{
"spec": {
"hard": {
"cpu": "3",
"pods": "10",
"secrets": "10"
}
}
}
```
For all application namespaces will be added resource quota:
```bash
$ kubectl --namespace test20 get quota
NAME           AGE
test20-quota   35m
$ kubectl --namespace test20 get quota -o yaml
apiVersion: v1
items:
- apiVersion: v1
kind: ResourceQuota
metadata:
labels:
app: test20
heritage: deis
name: test20-quota
namespace: test20
spec:
hard:
cpu: "3"
pods: "10"
secrets: "10"
status:
hard:
cpu: "3"
pods: "10"
secrets: "10"
used:
cpu: "0"
pods: "0"
secrets: "1"
kind: List
metadata: {}
```
We need this PR to restrict users from creation applications with a lot of resource usage. In our …

Add basic support of resource quotas for applications

---

rootfs/bin/boot

This is a better fix for issue #804 and fixes #1170:
* The gid of the docker socket is no longer changed to that of the deis group (gid 107).
* If an existing group in the container has the same gid as the socket, we add the deis user to that group (unless of course it is the "deis" group).
* If no such group exists, we create a new "docker" group and add the user to that (like before @bacongobbler's hack in b27c816e9ef21a989c68db23c0c98c02f726cf7b was added, which effectively disabled this code).

fix(boot): Don't change group ownership of docker socket

---

rootfs/api/models/app.py
rootfs/api/models/release.py
rootfs/scheduler/mock.py
rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/pod.py
rootfs/scheduler/tests/test_deployments.py

In versions prior to Kubernetes v1.5, an empty list was returned when a resource didn't exist. in
v1.5 it now returns a NoneType, so we need to account for that change and convert it back to an
empty list.
fixes #1175

fix(api): account for NoneType when resource is gone

---

rootfs/api/migrations/0001_initial.py
rootfs/api/migrations/0002_auto_20151215_0352.py
rootfs/api/models/__init__.py
rootfs/api/models/app.py
rootfs/api/tests/test_app.py

An application name must start with an alphabetic character and cannot end with a hyphen.
closes #1160

fix(api): validate app name against k8s service regex

---

rootfs/api/tests/test_perm.py
rootfs/api/urls.py

fixes #1180 
There are no restrictions while creating users and hence there should be any while changing the perms of the user.

fix(perms):Use the same regex for perms as auth endpoint

---

codecov.yml

This way, changes that drop coverage by less than a fifth of a percent will still pass. Anything
more than that should be looked at more closely by the reviewer for more potential places to cover
with tests.
This is mostly so that small PRs that shuffle some code around won't fail. As a reference point for how large 0.2% is in terms of code coverage, PRs like #1191 will still fail.

ref(codecov): add 0.2% failure threshold to codecov

---

rootfs/api/models/certificate.py
rootfs/api/tests/test_certificate.py
rootfs/api/tests/test_certificate_use_case_1.py
rootfs/api/tests/test_certificate_use_case_2.py
rootfs/api/tests/test_certificate_use_case_3.py
rootfs/api/tests/test_certificate_use_case_4.py
rootfs/api/tests/test_certificate_use_case_5.py

feat(api): validate a certificate's private key

---

charts/controller/templates/controller-deployment.yaml
rootfs/api/settings/production.py

closes https://github.com/deis/deis/issues/5113

Get timezone from environment variable

---

charts/controller/templates/controller-deployment.yaml

Changes in #1196 created problems for me when deploying master charts:
```shell
$ helm install --namespace deis ./charts/controller/
Error: parse error in "controller/templates/controller-deployment.yaml": template:
controller/templates/controller-deployment.yaml:79: malformed character constant: 'UTC'
```
This fixes that error by following `default` template usage [guidelines for pipelining](https://github.com/kubernetes/helm/blob/master/docs/chart_template_guide/functions_and_pipelines.md#using-the-default-function). Works fine after this change.
```shell
$ helm install --namespace deis ./charts/controller/ 
NAME:   ringed-chicken
LAST DEPLOYED: Sun Jan 15 11:19:37 2017
NAMESPACE: deis
STATUS: DEPLOYED
...
$ helm upgrade ringed-chicken ./charts/controller/ --set …
```

fix(charts): pipeline time_zone value to quote func

---

rootfs/Dockerfile

I'm unable to build the controller container from master due to a `gunzip` error:
```shell
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
gzip: /usr/share/copyrights.tar.gz has 19 other links -- unchanged
tar: Removing leading `/' from member names
tar: Removing leading `/' from hard link targets
gzip: /usr/share/copyrights.tar.gz already exists;	not overwritten
```
This is probably related to switching from `ubuntu-slim` to `ubuntu` in deis/docker-base#22 somehow--see also #1197. Adding a `-f` flag seems to fix it for me.

fix(Dockerfile): force gunzip of copyright archive

---

charts/controller/templates/controller-deployment.yaml

On some providers, "localhost" is not set up on the host network. explicitly calling the loopback
address fixes this.
See https://github.com/deis/workflow/issues/678

fix(charts): reference registry-proxy on 127.0.0.1

---

rootfs/requirements.txt

From the requests library release notes:
Features
- Only load the idna library when we've determined we need it. This will save some memory for users.
Miscellaneous
- Updated bundled urllib3 to 1.20.
- Updated bundled idna to 2.2.

chore(requirements): update requests to 2.13.0

---

rootfs/scheduler/mock.py
rootfs/scheduler/resources/deployment.py
rootfs/scheduler/resources/events.py
rootfs/scheduler/resources/pod.py
rootfs/scheduler/tests/test_deployments.py
rootfs/scheduler/tests/test_pods.py

This PR handle 2 specific cases:
- User did not set quota for applications or set it incorrectly
- User tries to scale the application when limits are already exceeded (overuse)
Аdmin set default quota for namespaces (memory request and limit to1024M).
User tries to deploy application my-shiny-app (w/o setting limits for application): git push deis master
Deis controller return success after build and launch, but actually no pods are started because kubernates rejects pods creation.
Kubernates controller manager add event message to namespace with description:
```
Error creating: pods "my-shiny-app-web-1758015041-" is forbidden: failed quota: my-shiny-app-quota: must specify limits.memory,requests.memory
```
If quota is enabled in a namespace for compute resources like cpu and memory, …

Handle cases with namespace quotas limits sets

---

rootfs/api/models/app.py
rootfs/api/tests/test_build.py

Or vice versa.
Closes deis/workflow#658.
~~This seems to fix things, but I need to write some unit tests to cover these cases, possibly write some e2e tests that cover this as well, and reassure myself that this doesn't create any regressions.~~ *Edit*: finally got back to this PR and after some refactoring, this change fixes this edge case.

fix(models/app): recreate proc types on switch from Dockerfile to buildpack

---

charts/controller/templates/controller-deployment.yaml
rootfs/api/models/app.py
rootfs/api/settings/production.py

Uses the k8s downward api to make the current namespace available to controller so it isn't hard-coded as "deis."
Closes #1246.
Closes deis/charts#18.
Closes deis/builder#483.

fix(app.py): use current namespace instead of "deis"

---

rootfs/requirements.txt

See http://pythonhosted.org/django-auth-ldap/changes.html#v1-2-9-2017-02-14-fix-python-ldap-incompatibility
and http://www.django-rest-framework.org/topics/release-notes/#354
and https://github.com/sigmavirus24/requests-toolbelt/blob/master/HISTORY.rst#071----2017-02-13

chore(requirements): update ldap, drf, and requests-toolbelt

---

rootfs/requirements.txt

See http://pythonhosted.org/psycopg2/news.html#what-s-new-in-psycopg-2-7-1

chore(requirements): update psycopg2 to 2.7.1

---

rootfs/api/utils.py

The decorator syntax for `asyncio` in python 3.4 was considered provisional and is superseded in python 3.5 by new keywords such as `async` and `await`. Controller already requires Python 3.5. This change makes some code a bit more readable and future-proofed.

ref(utils): use python 3.5 asyncio keywords

---

charts/controller/templates/controller-deployment.yaml
charts/controller/templates/controller-ingress-rule-http-80.yaml
charts/controller/values.yaml
rootfs/api/models/app.py
rootfs/api/settings/production.py
rootfs/scheduler/resources/ingress.py

This replaces #1243 by patching a coercion to `bool`. All credit to @kris-nova of course.
Work for experimental native ingress. Run the documentation in https://github.com/deis/workflow/pull/732 to see how to use the new feature.
This PR handles the changes necessary to the controller to start managing Kubernetes ingresses
Requires deis/workflow#782
Requires deis/builder#495
Requires deis/router#316

feat(ingress): experimental native ingress

---

Makefile
rootfs/dev_requirements.txt

I added `make test-unit-quick` long ago as a developer convenience when I saw that Django's test framework had a `--parallel` flag. But this target seems to have rusted over time; I get multiple failures on every run--errors that don't appear with `make test-unit`.
This target isn't referenced in CI (and I never really used it), so let's simplify life by removing it and the `tblib` package it needed.
Closes #1273.

chore(Makefile): remove broken "test-unit-quick" target

---

.gitignore
.travis.yml
Makefile
rootfs/.coveragerc
rootfs/Dockerfile.test
rootfs/api/settings/testing.py
rootfs/bin/test-style
rootfs/bin/test-unit
rootfs/dev_requirements.txt

Coerces `make test-style` and `make test-unit` to run in containers, which avoids the need to have Python 3.5 and the packages in `dev_requirements.txt` on your local workstation. Also updates the fork of requests-mock to that in the deis org.
Closes #18.
Closes #1049.
See also deis/docker-python-dev#11 and deis/dockerbuilder#120. If that approach is acceptable, this could be refactored similarly for `make test-style` at least.

feat(Makefile,rootfs): run unit and style tests in container

---

rootfs/api/middleware.py
rootfs/api/settings/production.py
rootfs/api/settings/testing.py
rootfs/api/wsgi.py
rootfs/requirements.txt

See https://www.djangoproject.com/weblog/2017/apr/04/django-111-released/ This is an LTS release of Django, so it's supported for three years.
I tested all the changed links to ensure they still point to relevant areas in the Django documentation.

chore(requirements): update Django to 1.11 LTS

---

rootfs/scheduler/mock.py
rootfs/scheduler/resources/ingress.py
rootfs/scheduler/tests/test_ingress.py

Adding unit tests for ingress
Non breaking change
closes https://github.com/deis/controller/issues/1275

chore(ingress): Adding unit tests

---

rootfs/requirements.txt

See https://github.com/litl/backoff/releases/tag/v1.4.2

chore(requirements): update backoff library to v1.4.2

---

rootfs/requirements.txt

From the CHANGES doc at https://github.com/pyldap/pyldap/blob/master/CHANGES:
----------------------------------------------------------------
Released 2.4.35 2017-04-25 (upstream)
Changes since 2.4.33:
(2.4.34 is missing because of foolish pypi version madness)
Modules/
* use errno in a safer way
* set errno as LDAPError class item
* do not use strerror() which is not thread-safe and platform-specific
Lib/
* LDAPObject._ldap_call() sets LDAPError info to value returned
by platform-neutral os.stderror()
----------------------------------------------------------------
Released 2.4.33 2017-04-25 (upstream)
Lib/
* faster implementation of ldap.schema.tokenizer.split_tokens()
(thanks to Christian Heimes)
* removed unused 2nd argument of ldap.schema.tokenizer.split_tokens()
* fixed method …

chore(requirements): update pyldap to v2.4.35

---

charts/controller/templates/_helpers.tmpl
charts/controller/templates/controller-clusterrole.yaml
charts/controller/templates/controller-clusterrolebinding.yaml
charts/controller/values.yaml

With this change deis-controller became available to work in RBAC-only clusters
Works with both Kubernetes 1.5 and 1.6 (see templates/_helpers.tmpl for details)
Actually tested with 1.5.7 and 1.6.4
ClusterRole allows deis-controller:
- namespaces: `get`, `list`, `create` and delete
- services: `get`, `list`, `create`, `update` and `delete`
- nodes: `get` and `list`
- events: `list` and `create`
- secrets: `list`, `get`, `create`, `update` and `delete`
- replicationcontrollers: `get`, `list`, `create`, `update` and `delete`
- replicationcontrollers/scale: `get` and `update`
- pods/log: `get`
- pods: `get`, `list` and `delete`
- resourcequotas: `get` and `create`
- apps/deployments: `get`, `list`, `create`, `update` and `delete`
- autoscaling/horizontalpodautoscalers: `get`, `list`, …

RBAC support

---

README.md

Adding a new link for getting started with k8s so developers can test by install with minikube or another platform.

Adding a working install-k8s link

---

rootfs/api/management/commands/load_db_state_to_k8s.py
rootfs/api/models/tls.py

fix(controller): Persist ssl.enforce header on service creation

---

rootfs/api/models/app.py

Fixes #1313
An unhandled exception in ns.create due to "Conflict namespaces" will wipe out an entire namespace. I've added a catch here to protect against that occurring.

fix(api/models/app): Catch unhandled error
